### ISSUE TITLE
Editor: Join on blank buffer causes crash

### ISSUE THREAD

**Issue by fpgaminer** [jkotlinski/durexforth#132]
In vi, executing join repeatedly on a blank file causes a hard crash (crashes back to BASIC and memory is corrupted).

After debugging it looks like join calls `nipchar`, which is the root cause.  It decrements `eof` even if the buffer is empty, which eventually leads to the crash if called repeatedly.  Also, it looks like `nipchar` is `cmove`-ing one more byte than it should.  It calculates the `cmove` length by subtracting eof from editpos and then adding 1.  Based on my understanding, adding one is wrong.  For example, a buffer with one character and editpos at the beginning will have an eof of 6003 and editpos of 6001.  So `nipchar` would call `cmove` with `( 6002 6001 3 )` but there are only two bytes to move (0d and 00).

Here is my modified version which fixes both issues:

```
: nipchar
editpos 1+
editpos
eof @ editpos -
dup 1 = if 2drop drop exit then
cmove 
ffff eof +! ;
```

Additionally, this bug affects the delete line command, since it calls `join-lines`.

**Comment by jkotlinski** [comment]
Hi! Thanks a lot. I had the feeling something was strange with join, but never understood what. I applied your change now with a few tweaks! All the best

**Comment by chitselb** [comment]
Johan?  Is this email reaching you?  I'm the guy doing
http://github.com/chitselb/pettil and I have a couple of questions
regarding a C=64 port

Charlie

**Comment by jkotlinski** [comment]
Hi Charlie, feel free to ask any questions :)

**Comment by chitselb** [comment]
Okay...

On the PETTIL zeropage on the PET, I swap out $00-$8C (inclusive) when I go
back and forth between BASIC and PETTIL.  (see 'Aloha'). What's the
available address range on the C=64?  I believe it's $02-$8D, after which
the Kernal starts to interfere.

What's your real email?  me = chitselb@gmail.com
