### ISSUE TITLE
Editor: backspace from blank line incorrectly places cursor

### ISSUE THREAD

**Issue by fpgaminer** [jkotlinski/durexforth#133]
When using vi in insert mode, backspacing while on a blank line will place the cursor incorrectly on the line above (the line you backspaced to).  It is placed on the last character of the line above, when it should be placed to the right of the last character.

For example, suppose the following file, where `[]` is used to indicate the character under the cursor:

```
Hello, Forth!
[ ]
```

Backspace pressed (in insert mode):

```
Hello, Forth[!]
```

One more backspace:

```
Hello, Fort[!]
```

The expected behavior is:

```
Hello, Forth![ ]
```

Followed by:

```
Hello, Forth[ ]
```

My patch is to modify the top of backspace like so:

```
: backspace
curx @ 0= if cury @ if
linelen 0= linelen 0<> cur-up eol linelen 0<>
join-lines
and if cur-right nipchar then if force-cur-right then then
exit then
```

I'm not confident that that will be correct in all usages of backspace, but a quick test shows that it is working.  It continues to fail outside insert mode, because the cursor cannot be to the right of the end of a line outside of insert mode.

**Comment by jkotlinski** [comment]
Something seems really broken here and your fix doesn't seem to fix it enough...

For example, I do s" foo" vi to enter editor, then enter "Hello Forth!<CR>" followed by backspace and the editor goes into endless loop :(

**Comment by fpgaminer** [comment]
I'm not able to replicate that.  Testing with commit 7fc6fde94ecbc595d29771fda34a6a9b0301016d, I apply my patch, do a `make clean && make`, load and run the disk in the VICE C64 emulator, wait for compilation to finish, type `s" foo" vi` followed by return, wait for vi to start, press `i`, type `Hello Forth!`, and finally press backspace.  No crash.  I then tested various other usages of backspace, and saw no crashes.

If you'd like, I can push the changes to a fork and submit a pull request for you to test, in case your local copy is different somehow.

**Comment by jkotlinski** [comment]
Hi, I fixed my issue now. The problem was uninitialized memory.

**Comment by jkotlinski** [comment]
I tried your patch now and it works too. Thanks a ton!
