### ISSUE TITLE
Editor: cur-down does not scroll the screen

### ISSUE THREAD

**Issue by fpgaminer** [jkotlinski/durexforth#134]
In vi, it looks like the cur-down function is not correctly scrolling the screen.  Tested in VICE C64 emulator and my own C64-like machine.  The culprit appears to be this [line](https://github.com/jkotlinski/durexforth/blob/master/forth_src/vi.fs#L153):

```
homepos next-line over @ !
```

If my understanding is correct, there is nothing on the stack before that line.  `homepos` will push the location of the `homepos` variable on the stack.  It is not read, so the address of the `homepos` variable is on the stack, not the value of `homepos`.  So `next-line` makes no sense.  After `next-line` the stack depth is 1, so `over` makes no sense.

Based on what I think that line was trying to do, this is my patch:

```
homepos @ next-line homepos !
```

That makes the screen scroll correctly on my test machine.

**Comment by jkotlinski** [comment]
Thanks, the patch seems to work, it's added...
