### ISSUE TITLE
vi.pet

### ISSUE THREAD

**Issue by polluks** [jkotlinski/durexforth#137]
First line scrolls always away.

**Comment by jkotlinski** [comment]
Hi! I guess this is a problem with long lines? >40 columns?

**Comment by polluks** [comment]
Indeed, it's gone if you delete the long line.

**Comment by jkotlinski** [comment]
so this is a dilemma because I am reluctant to add more code to handle the long lines case. maybe it is better in the end to just assume there will be no long lines? and save some RAM

**Comment by polluks** [comment]
it's your decision: feature vs. resources

**Comment by jkotlinski** [comment]
I acknowledge the problem but putting it as won't fix for now

**Comment by polluks** [comment]
Screen refresh was better in the past...

**Comment by chitselb** [comment]
I got around this by using the built-in screen editor, which is very Forthy.

**Comment by jkotlinski** [comment]
@polluks Do you have any problems besides the 40-column issue? For me the screen refresh (especially scrolling up/down) seems a lot faster now. Before it was painfully slow.

**Comment by jkotlinski** [comment]
@chitselb What is the built-in screen editor?

**Comment by chitselb** [comment]
The ROM editor.  The blinking cursor with cursor direction controls, as in,
when you turn the machine on.  Search for 'name=(EDIT)' at
https://github.com/chitselb/pettil/blob/master/src/pettil-editor.a65

**Comment by jkotlinski** [comment]
@chitselb That's pretty clever :)  There is the limitation of not being able to edit things larger than 40*25 characters, but if one is fine with that, it seems like a good idea.

**Comment by chitselb** [comment]
It goes back to that whole blocks vs. files holy war, which the files folks
seem to have one.  I'm coming at Forth from a more oldschool perspective
than someone who came up with ANS-draft Forth

**Comment by chitselb** [comment]
"seem to have won" even :)

**Comment by jkotlinski** [comment]
@chitselb I am not sure the durexforth "vi" editor is very good. But what I am pretty convinced is that the Blazin' Forth way of doing things, storing all blocks raw on disk, is something I don't like at all. C64 already has an inbuilt file system. and it seems wrongheaded to be incompatible with the rich ecosystem of C64 tools that depend on it.

I think Turbo Assembler is a good example for a C64 programming environment that is both simple, productive and fun. It would be impossible to get the same nice experience using blocks and one-screen editing, and essentially I don't see why Forth users should settle for less.

Having said that I am having huge doubts that my own editor is anywhere near good enough :)

**Comment by chitselb** [comment]
It's a very familiar editor. My "blocks" are cached in memory and written
to cassette tape as PRG files
