### ISSUE TITLE
Std comment character

### ISSUE THREAD

**Issue by polluks** [jkotlinski/durexforth#140]
How about using ASCII \ and PETSCII £?

**Comment by jkotlinski** [comment]
Hallo! I agree that '#' isn't great. But '£' is even worse for me, it is not present on Swedish keyboards.

At least '#' (and possibly '%') are used as comment sign in some languages.

**Comment by polluks** [comment]
In VICE it's the insert key http://www.waitingforfriday.com/images/thumb/7/71/C64Keyboard_VICE_KB.png/600px-C64Keyboard_VICE_KB.png
on host you simple type backslash...

**Comment by jkotlinski** [comment]
Well yes but it's weird that the PETSCII != ASCII... it would make the documentation a bit strange...

**Comment by polluks** [comment]
Every PET has a pound key, using non-standard encoding. That's the way it is, you are free to use it :-)

**Comment by jkotlinski** [comment]
It's a nice idea and I tried it out now. It's great to have the \ on PC, but £ as a comment just looks very weird on the C64 to me :/

**Comment by jkotlinski** [comment]
Maybe % would be better than # ? It looks a little bit nicer and also % is not part of ANS forth

**Comment by polluks** [comment]
Hmm, ASCII \ and PETSCII £ share the same code, so there would be no translation.

**Comment by jkotlinski** [comment]
Translation or no translation is not a problem. The only problem that I have is that I think the PETSCII £ looks weird to use as a comment character :-)

**Comment by polluks** [comment]
You are talking about the esthetic point of view? It's an eyecatcher :-)

**Comment by chitselb** [comment]
Blazin' Forth uses // but I would stick with hex 5C (backslash on most
systems or british pound symbol on a US keyboard C=64)

**Comment by jkotlinski** [comment]
Ok, I believe in democracy so I did the change now :)  Thanks!

**Comment by radiofreejohn** [comment]
I know this issue is closed, but as I was reading the durexForth manual, I ran into the pound symbol and wondered if something weird happened with LaTeX - but figured it may be an encoding thing. This discussion is helpful, and it may be worth calling this quirk out in the durexForth manual when it first appears so other readers aren't confused.
