### ISSUE TITLE
Include version in executable

### ISSUE THREAD

**Issue by polluks** [jkotlinski/durexforth#151]
Something like this...

Makefile:
```echo !word `svnversion` >version.a```

durexforth.a:
`!byte $b, $08, $a, 0, $9E, $32, $30, $36, $31, 0, 0, 0 ; basic header`
-->
`!byte $b, $08`
`!src "version.a"`
`!byte $9E, $32, $30, $36, $31, 0, 0, 0 ; basic header`

**Comment by jkotlinski** [comment]
Hi! I'm not interested in spending time on adding this right now, as I am working on other interesting stuff, but you are welcome to submit a pull request :)

**Comment by jkotlinski** [comment]
@polluks I changed it now so that the disk label contains the version name. Any particular advantage you see in also having it in the executable?

**Comment by polluks** [comment]
It's ok, thanks.

**Comment by jkotlinski** [comment]
OK, added the svn fallback. Thanks!
