### ISSUE TITLE
Tick

### ISSUE THREAD

**Issue by polluks** [jkotlinski/durexforth#156]
Brodie says: If tick cannot find a word in the dictionary, it executes ABORT" and prints an error message.
' xxx .
says 3

**Comment by jkotlinski** [comment]
@polluks Forth 2012 standard does not prescribe any behavior for this.

http://forth-standard.org/standard/core/Tick

**Comment by jkotlinski** [comment]
...on the other hand. Forth 2012 standard says that when interpreting, `' foo execute` should give the same effect as `foo`. So yes, maybe some work to be done there :)

**Comment by polluks** [comment]
Fine. Merry Christmas!

**Comment by jkotlinski** [comment]
Guten Rutsch!

**Comment by polluks** [comment]
Anyway debugging will be easier if nonsense is not ignored.

**Comment by jkotlinski** [comment]
Fixed!
