### ISSUE TITLE
Mixed sign division

### ISSUE THREAD

**Issue by polluks** [jkotlinski/durexforth#157]
-123 123 / .
123 -123 / .

**Comment by jkotlinski** [comment]
http://www.figuk.plus.com/build/arith.htm

**Comment by polluks** [comment]
I see, it's the same in Open Firmware. Maybe you write a note in the docs?

**Comment by jkotlinski** [comment]
No, I plan to fix it :)  This was just a bookmark for how to do it...

**Comment by jkotlinski** [comment]
fixed!
