### ISSUE TITLE
REFILL is non-standard

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/durexforth#169]
should be REFILL ( -- flag ) where true if successful, false if no lines left in stream

**Comment by chitselb** [comment]
This thread might be interesting/helpful.

https://groups.google.com/d/msg/comp.lang.forth/73Lu_SRSv6k/FT60VYtR3awJ

**Comment by jkotlinski** [comment]
Thanks for the link! Somehow I haven't read that. Nice job debunking the myth that Blazin' is STC.

It was a lot of work to rewrite the input so that it uses standard SOURCE / >IN / REFILL et.c., but totally worth it. Very flexible and fun to use.

**Comment by jkotlinski** [comment]
"When the input source is a text file, attempt to read the next line from the text-input file. If successful, make the result the current input buffer, set >IN to zero, and return true. Otherwise return false."

**Comment by jkotlinski** [comment]
"When the input source is the user input device, attempt to receive input into the terminal input buffer. If successful, make the result the input buffer, set >IN to zero, and return true. Receipt of a line containing no characters is considered successful. If there is no input available from the current input source, return false.

When the input source is a string from EVALUATE, return false and perform no other action."

**Comment by jkotlinski** [comment]
probably makes sense to keep it as is, since EVALUATE is used for vi f7
