### ISSUE TITLE
"flash" example modifies both foreground and background colours

### ISSUE THREAD

**Issue by Balooga** [jkotlinski/durexforth#176]
> : flash begin 1 d020 +! again ; flash

From the manual, the above flashes both the screen foreground & background.  Is this because "+!" assumes a 16-bit number at the specified address?

**Comment by polluks** [comment]
correct

**Comment by jkotlinski** [comment]
yes, that is the expected behavior

**Comment by Balooga** [comment]
Thank you.

A somewhat related question; will the operation "c!" pop 16-bits from the stack, only writing the lower 8-bits to memory? Or will it pop only 8-bits from the stack.  The manual is not clear on this.

**Comment by jkotlinski** [comment]
The stack contains cells, which are always 16-bit.
