### ISSUE TITLE
Test code blows stack

### ISSUE THREAD

**Issue by Balooga** [jkotlinski/durexforth#181]
I'm not sure why my code blows the stack.  Could anyone provide some feedback?

> : wait-raster ( - )
> begin until d012 c@ 32 = ;

> : test ( - )
> begin depth . wait-raster depth . again

**Comment by jkotlinski** [comment]
: wait-raster ( - )
begin d012 c@ 32 = until ;

works like it should.

**Comment by Balooga** [comment]
Thank you.

**Comment by jkotlinski** [comment]
You will probably notice, Forth is too slow to match the raster line like that. Code like wait-raster should better be written in assembly.
