### ISSUE TITLE
cartridge: make possible to switch out $a000-$bfff

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/durexforth#183]
not sure if this is practically possible without also switching out Kernal.

**Comment by jkotlinski** [comment]
not sure if this is practically possible without also switching out Kernal.

**Comment by polluks** [comment]
https://groups.google.com/d/msg/comp.sys.cbm/WLlpijJ8ZDk/yPGNRGrXrQcJ

**Comment by jkotlinski** [comment]
That thread adds more confusion than it does not :)

I will probably keep it like it is. Plain 16 kByte ROM has the benefit that it is compatible with most emulators and hardware.

**Comment by jkotlinski** [comment]
Fixed. Now uses Simons' Basic cart type.
