### ISSUE TITLE
Editor: * find

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jkotlinski/durexforth#19]
```
Find word under cursor position
```

Original issue reported on code.google.com by `kotlin...@gmail.com` on 12 Jan 2009 at 4:34

**Comment by polluks** [comment]
Just FYI http://forum.6502.org/viewtopic.php?f=9&t=4364

**Comment by jkotlinski** [comment]
Oh... this ticket is a bit unclear. It is about search in the editor, * command in Vim: http://vim.wikia.com/wiki/Searching

**Comment by polluks** [comment]
I know, I just want to save the interesting link somewhere.
And how about this? http://forum.6502.org/viewtopic.php?f=9&t=4294
