### ISSUE TITLE
IDE64 crash when saving file in vi by typing :w!<any char>

### ISSUE THREAD

**Issue by johangroth** [jkotlinski/durexforth#193]
I'm using Vice 2.4 with Ide64 (idedos v.090 patch 51) and reu 512k enabled. Every time I try to save something in vi with `:w!<some char>` where `<some char>` is just any key press I end up in idedos monitor. Is this a know problem? 
I have to admit that I've modified the code so I can use device number from 12-14.
But is also crashed when I'm using device 8 (so slow).

My change:

```
$ git diff 
diff --git a/disk.asm b/disk.asm
index 33b6daf..243b9cc 100644
--- a/disk.asm
+++ b/disk.asm
@@ -167,8 +167,8 @@ load_binary_laddr_hi = *+1
 .disk_io_setnamsetlfs ;reused by both loadb and saveb
     jsr SETNAM
     lda $ba            ;last used device number
-    and #3             ;Make 0-3 possible numbers
-    ora #8             ;Transform to 8-B
+;    and #3            ;Make 0-3 possible numbers
+;    ora #8            ;Transform to 8-B
     tax
     lda #1
     ldy #0             ;if load: 0 = load to new address, if save: 0 = dunno, but okay...
```

**Comment by jkotlinski** [comment]
Hi! It's not been tested with IDE64 so it might very well be that some code (in disk.asm/vi.fs) would need to be rewritten. Contributions are welcome.

**Comment by johangroth** [comment]
Hi Johan,
It is indeed the IDE64 that causes the problem. I removed it from the
emulation and saving a file from vi works just fine. Need to find some time
to make durexforth compatible with IDE64.

Regards,
Johan

**Comment by Whammo** [comment]
If IDE64 causes an NMI this would cause the crash. IDE64 definitely requires control of the vectors, and DurexForth definitely stubs the  NMI vector.

**Comment by Whammo** [comment]
I found an article. IDE64 might be compatible now 

[ http://c64os.com/post/supportingide64 ]

**Comment by jkotlinski** [comment]
Anyone has possibility to test if this is now fixed?

**Comment by Whammo** [comment]
It works with 3.0.0 in vice emulation if you set IDE device to 10. V Load/save no problem.

**Comment by Whammo** [comment]
Actually:
:w! without a filename errs, even without IDE64
:w     Doesn't seem to save-with-replace
:w!@0:filename   This works

**Comment by Whammo** [comment]
http://www.ide64.org/ide_fix.html

**Comment by jkotlinski** [comment]
Let's assume it works fine then? Thank you for the help :-)
