### ISSUE TITLE
optimize * /

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/durexforth#194]
They are pretty slow compared to Blazin' Forth. Reference: https://theultimatebenchmark.org/

**Comment by burnsauce** [comment]
Are you talking about the two words `*` and `/` or are you talking about the word `*/`?

**Comment by burnsauce** [comment]
Oof, had a look at `*`.  While durexforth's `UM*` is faster than blazin' forth's, the `*` is like 60% slower on durexforth.  Blazin's `*` is machine code, whereas durexforth uses forth.  On blazin', `*` -> `UM*` has very low overhead.

Are there differences in the '83 spec that could account for more of this shortfall?  Precision, etc.

**Comment by jkotlinski** [comment]
so multiply is fixed. division is still outstanding problem, right?
