### ISSUE TITLE
save-forth to work with the cartridge version

### ISSUE THREAD

**Issue by cminter** [jkotlinski/durexforth#196]
I don't think `save-forth` works when running via cartridge.  I see it just does a simple `saveb`.

For example a saved app doesn't work in this case:

1. attach durexForth cartridge and boot
2. in durexForth, save app with `s" myapp" save-forth`
3. detach cartridge
4. in BASIC, load app with `load "myapp", 8`
5. then `run`

Is it feasible that `save-forth` could be modified to work in this case?
If not maybe either remove `save-forth` from the cartridge image or print an error when used?

What do you think?

**Comment by jkotlinski** [comment]
Thanks for the report! It's now fixed!
