### ISSUE TITLE
Use HERE instead of separate WORD_BUFFER

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/durexforth#197]

**Comment by jkotlinski** [comment]
The problem description is maybe too vague. WORD_BUFFER is not necessarily bad - for one thing, it makes sure that the contents stay valid until WORD is called again. Leaving things like is.

**Comment by jkotlinski** [comment]
fixed this now anyway!!

**Comment by Kroc** [comment]
Nice work, some much cleaner code to examine :)

**Comment by jkotlinski** [comment]
Thanks for the encouragement! Right, it feels like PARSE-NAME/FIND-NAME
makes things so much cleaner.
