### ISSUE TITLE
NEWBIE: getting this to work on a the64 mini 

### ISSUE THREAD

**Issue by free-variation** [jkotlinski/durexforth#207]
Greetings,

I have just received a 1/2 sized C64 clone called a "the64 mini".  Now I would like to grow beyond its very limited BASIC and have true graphics primitives.  

Would this work?

**Comment by polluks** [comment]
For sure, just copy the d64.

**Comment by free-variation** [comment]
Fantastic -- will try this weekend and report back.  Thank you!

**Comment by jkotlinski** [comment]
Was everything OK?
