### ISSUE TITLE
Vi: R

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/durexforth#210]

**Comment by burnsauce** [comment]
After several factoring attempts, I don't think this feature will fit in the cartridge ROM as it stands.

**Comment by jkotlinski** [comment]
Oh! Don’t worry too much about cartridge size. I can probably find some
bytes somewhere else :-)

**Comment by burnsauce** [comment]
This keycmd has been added now!

**Comment by jkotlinski** [comment]
Excellent 👍
