### ISSUE TITLE
Two includes within one line

### ISSUE THREAD

**Issue by polluks** [jkotlinski/durexforth#211]
`include gfx include gfxdemo` does not work,
screenshot follows...

**Comment by polluks** [comment]
![bug](https://i.ibb.co/NprfPyB/gfx.png)

**Comment by jkotlinski** [comment]
Clearly a bug. A fix could be to let each file have its own text input
buffer. Thanks for reporting!

**Comment by polluks** [comment]
Ok. You know, the line is part of the tutorial.

**Comment by jkotlinski** [comment]
Oops!.. what a terrible first impression

**Comment by polluks** [comment]
BTW what do you do if the filename contains spaces?

**Comment by jkotlinski** [comment]
Then use INCLUDED

**Comment by jkotlinski** [comment]
Fixed in 1.6.7!
