### ISSUE TITLE
immediate vs editor compile and run

### ISSUE THREAD

**Issue by cminter** [jkotlinski/durexforth#212]
this works in immediate entry:  1 1 + .
but this:  1 1 1 + + .
doesn't and gives an error:  "+ + .?"

but if I enter both in the editor, then compile and run it works.  output: 2 3

tested in v1.6.6 and 1.6.7

**Comment by cminter** [comment]
similarly for something like:  1 2 3 * * .
gives error:  "* * .?"

**Comment by polluks** [comment]
cannot reproduce...

**Comment by jkotlinski** [comment]
This is because SHIFT+SPACE produces a non-breaking space, gluing the different words together.
In a way, this is a useful and rational behavior. Nevertheless it can be very confusing, so I made a fix in 1.6.8. Thanks for reporting!

**Comment by cminter** [comment]
I wasn't noticing that I pressed shift+space.  I don't mind the original behavior now that I understand what happened.  Maybe if it is just documented the original behavior is fine.

**Comment by jkotlinski** [comment]
I checked with some other Forths (64forth, blazin’ forth) and they do
handle shift+space like space. So it seems like common and good practice to
do it like that. Let’s keep it :)
