### ISSUE TITLE
Suggestion `<more>` should be in reverse chars

### ISSUE THREAD

**Issue by Kroc** [jkotlinski/durexforth#217]
Minor suggestion: when the screen pauses scrolling, such as when invoking `words`, the `<more>` prompt could be in inverse (solid background) characters to better indicate that it's a prompt, and not a word in the list.

![image](https://user-images.githubusercontent.com/142650/66261763-26fcf480-e7cb-11e9-85fd-72355391babd.png)

**Comment by jkotlinski** [comment]
Nice idea! If you would like to make a pull request, I’d be happy to merge
it in. Or I can make the change myself when I find the time.

**Comment by Kroc** [comment]
This would be the line in question;

https://github.com/jkotlinski/durexforth/blob/b6e298c5cb182583d1027458ce537aa0073210d9/forth_src/debug.fs#L88

But, the inverse used for errors is done within the ASM:

https://github.com/jkotlinski/durexforth/blob/b6e298c5cb182583d1027458ce537aa0073210d9/durexforth.asm#L1125-L1138

(Somehow the inverse is turned off, but I don't see it!)

Assuming that printing within Forth scripts is using PETSCII codes, and not screen codes, the fix should be to output the inverse on|off code, like so:

```forth
: more d6 c@ 18 = if $12 emit ." <more>" $92 emit
```

, I think.

**Comment by jkotlinski** [comment]
fix is now in master. thanks!
