### ISSUE TITLE
Add LICENSE.txt

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/durexforth#223]
Add a file that clearly states the license of the files in this project, including any third party code that went in.

**Comment by burnsauce** [comment]
This should be a bit easier now.  With the `UD/MOD` rewrite, we are free of gforth code (I think!), eliminating a lot of the license documentation work.

**Comment by jkotlinski** [comment]
I believe the "FIG UK" code is from here : http://www.figuk.plus.com/build/arith.htm
