### ISSUE TITLE
Incompatible with Starting Forth?

### ISSUE THREAD

**Issue by burnsauce** [jkotlinski/durexforth#224]
Hi, I'm trying to learn FORTH using durexforth and Starting Forth.  (This isn't an issue with durexforth, per se, except that the documentation is misleading)

I'm encountering issues executing the examples in the text, with words not recognized by the interpreter, starting with words related to double integers, such as appending a . to integers to mark them as double, and using D. to print them out in chapter 7.

If core forth does not include this set of double-related words, how should I proceed to learn FORTH?  It's going to be hard to proceed if Starting Forth relies on these words later in the text.

Additionally, it seems 2DROP is implemented but not 2SWAP or 2OVER?  Maybe I'm missing something....

**Comment by jkotlinski** [comment]
Hi!
I guess I could add the missing words. But a more convenient option for
trying out the missing words might be to use some other Forth. There are
many good ones to choose from,
I have used Gforth myself because it is open source.
Cheers

**Comment by burnsauce** [comment]
I'm really loving working directly on the C64 (which is why I chose working with this over acmeforth), so it would be nice if durexforth was "compatible" so-to-speak with the recommended learning text.

I found some 2-words in compat, and that clears up some of the problems.  Is working with doubles uncommon / not intended in this implementation?

Adjacent to the "learning" half is the using half.  Should I go learn gforth, for example, I will still face the missing words issue if I go to use it.

(Unsaid so far is that I already develop asm on the C64 and wanted to learn forth FOR the C64.  I already tried some vintage carts before I found durexforth.)

**Comment by jkotlinski** [comment]
Yeah, well there is no real masterplan behind which words are supported or
not. I only implemented the words required by the standard or that I found
useful.
Personally I never felt the need to use 32-bit numbers for the stuff I’m
doing on the C64. 16 bits seems more than enough :-)
Also I thought it is probably better to provide less than more. Part of the
fun with Forth is that you get to customize things and add what you want.
Having said that, I think it might be easy to add D., it something that
would fit fine in compat.fs or some other file that can be optionally
included.

**Comment by burnsauce** [comment]
I've just encountered a word that is in 2012 core but not in durexforth or compat.fs: U.R

Is this an oddball or are there a set of "core" words that I should expect not to work here.

**Comment by jkotlinski** [comment]
U.R is in ”core extension” which is a set of core words that are not
required.

**Comment by burnsauce** [comment]
Thank you for clearing that up (and for helping a language noob!)
I'm okay that you close this issue when you're satisfied.

**Comment by jkotlinski** [comment]
OK!
