### ISSUE TITLE
Unnamed buffer becomes uneditable with vi

### ISSUE THREAD

**Issue by burnsauce** [jkotlinski/durexforth#226]
The unnamed buffer state can become corrupted when deleting (last?) line with dd.

Steps to reproduce:

1. Boot from crt
2. vi
3. Enter a single line of forth
4. press F7
5. vi
6. dd -> terminal displays "eof"
7. vi
8. i -> vi exits and terminal displays "eof"

vi is unusable until a file is loaded

I can't reproduce this bug with a named file.

**Comment by jkotlinski** [comment]
Thanks for reporting!
Apologies for not fixing ASAP, I’m busy with another project at the moment.
But will definitely sort this out.

**Comment by jkotlinski** [comment]
Should be fixed in master! Thanks for the report!
