### ISSUE TITLE
Possible Extensions

### ISSUE THREAD

**Issue by gitjeff2** [jkotlinski/durexforth#228]
First off, you have a *very cool* set of projects here. I just want to say that you might consider two extensions to Forth:

1. [An infix syntax for Forth](http://www.complang.tuwien.ac.at/anton/euroforth/ef08/papers/haley.pdf). That way those who are put-off by RPN have an alternative.
2. [Gfroth-style Object-oriented Forth](https://www.complang.tuwien.ac.at/forth/gforth/Docs-html/Object_002doriented-Forth.html). I haven't tried it, but from what I have read it's a small and flexible object system.

**Comment by jkotlinski** [comment]
Hi!
Thank you for kind words and interesting links!
I do not think I would be keen on implementing these modules myself, but
would be interested in accepting as contributions.
All the best
J
