### ISSUE TITLE
Fails to build if Drive 8 is set to read-only in VICE config

### ISSUE THREAD

**Issue by raydeejay** [jkotlinski/durexforth#229]
The generated binary saves to fail to disk, if the default X64 configuration happens to have drive 8 set to read-only. It would be good to pass enough command line options to set up a VICE environment that ensures a successful build, maybe simply `-default` and perhaps enable warp mode too.

**Comment by jkotlinski** [comment]
Good idea. I would be happy to accept this change as a pull request!

**Comment by raydeejay** [comment]
See #230 :-)

**Comment by jkotlinski** [comment]
Thank you!!
