### ISSUE TITLE
V editor corruption

### ISSUE THREAD

**Issue by raydeejay** [jkotlinski/durexforth#232]
It is my understanding that, according to the memory map in the documentation, it should be able to handle up to 12Kb. However, when the source grows to around 4Kb things start to break.

I've also noticed that memory at $a000-$c000 (at least) will get corrupted when entering and exiting the editor, even if there's no source loaded and `:q` is immediately issued.

Running both from cartridge and floppy in VICE, both with a default setup and with JiffyDOS, 1541-II drives.

**Comment by jkotlinski** [comment]
Hi!
Thanks for report. :q accidentally switched in BASIC to $a000-$c000. I corrected that now. Could you check if it fixes the problems?

**Comment by raydeejay** [comment]
I only tested it a bit, but both problems seem fixed with these changes!

**Comment by jkotlinski** [comment]
Fantastic! Thanks for reporting!
