### ISSUE TITLE
[FR] Markers to unload some (or all?) of the parts of the system easily

### ISSUE THREAD

**Issue by raydeejay** [jkotlinski/durexforth#238]
Basically it's about unloading the editor without unloading the rest of the system. This frees around 6Kb or 40% of dictionary space. It would be best to load it last during the build process, so `require` can remain loaded after the editor is unloaded.

The rest of the modules, in my opinion, are useful enough for everyone that most of the time one wants them loaded, and in the rare cases in which they are not wanted, the `modules` marker should be enough. If such an environment is required regularly, a custom image can be saved easily.

Going a step further, perhaps provide default definitions for `bufstart` and `eof` so programs can be written without having to special-case for whether the editor is loaded or not.

**Comment by jkotlinski** [comment]
I added an `---editor---` marker now, and documented this in the tutorial. Thanks for the suggestion!
