### ISSUE TITLE
[V] Typing something after issuing `:w!`, then cancelling, modifies the filename

### ISSUE THREAD

**Issue by raydeejay** [jkotlinski/durexforth#241]
To reproduce, open a file named `foo`, type the sequence `:w!a{delete}{return}`, then type `:w{return}`

**Comment by jkotlinski** [comment]
Fixed. Thanks for reporting it!

**Comment by jkotlinski** [comment]
I don't really like the "v" name by the way, but at least it's fast to type.

**Comment by raydeejay** [comment]
:rofl: ForthOS' editor is also called `v`, it's similar
