### ISSUE TITLE
`REQUIRE` marks a file as included even if it didn't find it on disk

### ISSUE THREAD

**Issue by raydeejay** [jkotlinski/durexforth#242]
To reproduce:

`REQUIRE non-existing-file`
`REQUIRE non-existing-file` again

**Comment by jkotlinski** [comment]
This behavior, while not great, is valid according to the standard:

An ambiguous condition exists if the named file can not be opened, if an
I/O exception occurs reading the file, or if an I/O exception occurs while
closing the file.

I realize another shortcoming of REQUIRED now - markers do not restore
REQUIRED state.

**Comment by jkotlinski** [comment]
Fixed both these issues now! Thanks for reporting!
