### ISSUE TITLE
SEE concatenates subsequent :NONAME

### ISSUE THREAD

**Issue by burnsauce** [jkotlinski/durexforth#246]
Reproduce:

```
: foo s" foobar" ;
ok
:noname s" noname" ;
ok
see foo
: foo s" foobar" exit s" noname" exit ;
ok
```

I don't know if this only affects SEE, or whether some other word may similarly misinterpret, but it does not affect EXECUTE, AFAICT.

**Comment by jkotlinski** [comment]
Interesting! Unfortunately, with the current setup, I do not think that
will be possible to resolve. Since :NONAME does not create a word header,
there is no information available that could be used to separate it from
the previous word.

**Comment by burnsauce** [comment]
Could SEE short-circuit when it meets EXIT?

**Comment by jkotlinski** [comment]
The ”problem” is that EXIT may very well be used inside a word, too... e.g.

: FOO IF EXIT THEN BAR ;

**Comment by burnsauce** [comment]
Ah! Should have thought of that.
This behaviour is perhaps worthy of an errata footnote in the docs.

Thanks again for :NONAME!  I've been playing with code relocation and it's pretty useful because I can move HERE around without having to perform dictionary surgery. :)

**Comment by jkotlinski** [comment]
great to hear! I suppose a problem with code relocation is that branches
are absolute, not relative? If needed I could probably change that.

**Comment by burnsauce** [comment]
It's code relocation via recompilation so I wouldn't need that change.  I've considered raw memmove relocation and by golly you would need a lot of introspection to do that right. :)

**Comment by jkotlinski** [comment]
true, even if the word itself is relocatable, it might be a slow process to
decompile each and every word to fix up the incorrect jumps.

**Comment by burnsauce** [comment]
Big props to the devs of the Jupiter ACE ROM.  I haven't looked at its memory efficiency, but EDIT blows my mind.

**Comment by jkotlinski** [comment]
I need to try that machine some day.
I am not sure about EDIT, but REDEFINE might be trivial to do in
Durexforth. A hacky but mostly working way would be to simply patch the old
word to jump to the new word.

**Comment by burnsauce** [comment]
It's quite a remarkable computing experience.  I highly recommend giving it a spin.  Kinda wish Durexforth used its line input idiom, but I understand that it leverages the C64 text editor.

**Comment by jkotlinski** [comment]
I played around with it a bit in an emulator now.
The EDIT thing is tremendously neat, however I would guess there is a price
to pay for this neatness, in terms of RAM usage and performance.
To some extent, you do have the same thing already in Durexforth. After
entering something into the interpreter, it’s fine to just go up with the
cursor and change it, then press enter to recompile, as long as it stays on
the screen.

**Comment by burnsauce** [comment]
One thing I really like is that the interpreter never says "ok" until you enter a semicolon while you're defining a word.

The other comparative shortcoming of Durexforth is that the interpreter can't read more than 2 screen lines at a time.

Anyhow I'm glad you experienced it. :)

**Comment by jkotlinski** [comment]
Good points. I changed it now so that ”ok” is not printed while compiling.
Not sure if it’s an improvement or not. More lines will fit on the screen
now, but the feedback is missing?

**Comment by burnsauce** [comment]
I agree that it's lacking feedback.  It's evident on the Jupiter ACE because there is only one valid input line: the bottom one.  With a navigable screen like the C64 editor, it doesn't quite make sense.  I feel like the only way to fix it is to ditch the C64 screen input idiom and that may not be in keeping with your goals for the project.

**Comment by jkotlinski** [comment]
The good part about reusing the Kernal for interpreter text input is that
there is working code in ROM already :)
About the V text editor, I am not entirely happy with it. Both in terms of
RAM usage and that there are two separate screens. It would maybe be nice
to have something line-based or a split-screen like some Forths do have.
A file-based EDIT/REDEFINE could work if each word was its own file. That
has its own problems though.

**Comment by burnsauce** [comment]
ex maybe? :)

**Comment by jkotlinski** [comment]
I tried to figure out what's left to do in this issue before closing.
I came to the conclusion, probably SEE's inability to handle :NONAME should be documented.
