### ISSUE TITLE
V not compiling

### ISSUE THREAD

**Issue by Whammo** [jkotlinski/durexforth#247]
https://github.com/jkotlinski/durexforth/blob/3d666f96954d474beaf06d1441ae4466ccb612c0/forth_src/v.fs#L562

this needs to be:
                                                 
2dup filename c! filename 1+ $f move

but wait- there's more-

326     $f openw $f closew
481     '!' emit here $f accept
471     'Z' of write-file $ffff exit endof
488     'q' of $ffff exit endof

That does it.

**Comment by jkotlinski** [comment]
fixed, thanks for report!
