### ISSUE TITLE
Add video links

### ISSUE THREAD

**Issue by polluks** [jkotlinski/durexforth#249]
[C64 Programming May the Forth be with you Pt 1 - YouTube](https://www.youtube.com/watch?v=TXIDqptXmiM)
[C64 Programming Into the Forth Dimension Pt 2 - YouTube](https://www.youtube.com/watch?v=1oZztCmC8kc)
based on 1.6.4

**Comment by jkotlinski** [comment]
Yes! Should be added to the README probably.
