### ISSUE TITLE
Using HERE as PAD

### ISSUE THREAD

**Issue by Whammo** [jkotlinski/durexforth#251]
I'm referring to the PAD word in 'Learning Forth'. 
It seems that some super-cool words from Format.fs are using HERE as PAD. There may be others.
 This hasn't become a problem yet- but it's something that might need to be worked around at some point. 
 The simplest solution is to create PAD, a value generally a fixed distance higher in memory and moves with HERE maintaining that distance.
 But, if it's not doing anything else, and if we're not going to deal with exceptionally long numbers, we could just as well put PAD to the cassette buffer.

**Comment by jkotlinski** [comment]
I agree that PAD would be useful. `$33c constant pad` seems like a fine solution!

**Comment by Whammo** [comment]
I have just tested the changes to V. W! deals with filenames as predicted, the pre-pended filename is correct in pad, and the filename saves correctly.

**Comment by Whammo** [comment]
*Closed pull request, copying note here for discussion.*
I did not (I believe) alter any Forth standard words, and although I might argue for Format.fs, Float.fs, and V.fs implementing non-standard words that use these spaces as a convenience for dealing with strings.
I also agree upon second thought. Format.fs and Float.fs, are not applications, but vocabularies. PAD should be not effected by these calls because if the user is in PAD he doesn't want these calls corrupting PAD.
However, V, being an user space application, ( Although systemic) there is no issue of concurrency in PAD, or HERE. And there is also no reason (other than using and demonstrating the use of PAD) to migrate V from HERE to PAD.
Agreed that Float.fs and Format.fs shall not use PAD.
I would like to appeal that V as an application should use PAD.
That said, it's not going to hurt my feelings if denied.
It's all fun, thanks guys!

**Comment by Whammo** [comment]
Maybe concurrency is the wrong word- replace that with corruption.

**Comment by jkotlinski** [comment]
Hi!
Sorry - I realize that copy-pasting wall of texts from the standard is not the most fun & friendly way to have a conversation :)  It may seem a bit passive agressive, but rest assured, all I try to do is to form some kind of opinion and communicate it in some way that is hopefully possible to understand.

I agree that from a technical standpoint it is completely reasonable that V uses PAD. The difficulty is, I think, documenting what does and does not use PAD?
I think the easiest would be e.g. "DurexForth never changes PAD or its contents. You can safely use it in your own applications without any risk of corruption."
Adding an exception for V makes for a weaker guarantee, and I am a bit unsure how to express it as clearly.

**Comment by Whammo** [comment]
Thanks- I'm grateful for your consideration. I am honestly enjoying every aspect of this process, and I understand that we all have lives, and other real projects. 
 I hope it doesn't seem that I am doing pathetic, picky little bits of code and asking for inordinate amounts of attention.
 I agree,  "DurexForth never changes PAD or its contents. You can safely use it in your own applications without any risk of corruption."  is the best policy.
 Thanks for taking the time to point out the aspects that I failed to consider.

**Comment by jkotlinski** [comment]
Great - I also enjoy - there is no other purpose to the project, so please
continue :-)

**Comment by jkotlinski** [comment]
PAD was added to master
