### ISSUE TITLE
Helping Others Learn Forth and Promoting DurexForth, too

### ISSUE THREAD

**Issue by gitjeff2** [jkotlinski/durexforth#261]
The language learning site <https://exercism.io/> Has a [ticket open](https://github.com/exercism/request-new-language-track/issues/67) indicating their willingness to add a Forth track to their site. Sadly, they don't have anyone to maintain it yet. This is one of two projects on GitHub that I thought of when I discovered this.

I realize DurexForth is niche, in that it's retro. But, retro is the new "cool." 

It's useful to show modern coders (who take terabytes of hard disk space and gigabytes of RAM for granted) just exactly what you can do with 64k of RAM with the right skills. Helping build live examples that can be used to learn Forth can only help DurexForth. It's a place that potential new contributors without a Forth background can be pointed to get up to speed quickly.

Similarly, the language learning site [Learn X in Y Minutes](https://learnxinyminutes.com/) has a [Forth document](https://learnxinyminutes.com/docs/forth/) but it's rather short. Growing the Forth talent base can only help this project and others like it.

**Comment by jkotlinski** [comment]
👍 I am busy with other stuff nowadays but I would be delighted to see someone pick it up!

**Comment by burnsauce** [comment]
The ticket referenced is closed, FYI, as the maintainer of Volksforth stepped forward.

**Comment by jkotlinski** [comment]
I will close this ticket as I do not plan any actions related to it. Thank you for asking though.
