### ISSUE TITLE
Promotion at EuroForth 2020?

### ISSUE THREAD

**Issue by polluks** [jkotlinski/durexforth#262]
See https://euro.theforth.net

**Comment by jkotlinski** [comment]
It’s a nice idea... i dreamed for many years to go to a real euroforth
conference...
Maybe Im old fashioned I dont understand how a video conference could
replace the real thing? But i should consider it maybe :-)

**Comment by polluks** [comment]
https://www.youtube.com/playlist?list=PLR1LOfn4ZiNesbuONckWzQ1vqd1QhDloI

**Comment by jkotlinski** [comment]
Thanks for sharing! I considered attending but it happened to collide with
some important IRL things...
