### ISSUE TITLE
document why £ is used instead of \

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/durexforth#263]

**Comment by gitjeff2** [comment]
That's a good question and it requires some technical background to explain...

ASCII `\` and PETSCII `£` both map to the glyph at byte $5c in their respective character sets. Further, there isn't a proper backslash `\` in PETSCII. So, it's not really possible to have a backslash without redefining a character bitmap.

In case you've spotted the character under the `M` key that superficially resembles a backslash, it's nearest Unicode equivalent is not the backslash you're familiar with but the [Box Drawings Light Diagonal Upper Left to Lower Right](https://www.fileformat.info/info/unicode/char/2572/index.htm) (U+2572), which looks like this: `╲`. If you look at `\` and `╲` side-by-side you'll note they're not the same.

While shenanigans like storing the backslash-like glyph under `M` as token code `£` but displaying it as the semi-graphical character `╲` are technically possible &mdash; [the BASIC screen editor in the C64 does this](https://www.c64-wiki.com/wiki/BASIC_token) with the *pi* `𝜋` character &mdash; that would add needless complexity to the text editor. Theoretically, someone could add a mode to the text editor to do this but I don't know how the DurexForth developers would feel about it. 

Perhaps others can chime in on this one, but that's the technical background behind the issue. So, in summary, the available options for dealing with it are: (a) leave it be, (b) redefine the `£` bitmap to look like `\` bitmap or (c) swap `£` with for display purposes only with pseudo-backslash `╲` every time it is encountered but store it as byte $5c. Does that make sense?

**Comment by jkotlinski** [comment]
yes :)  I thought it would be good to mention something in the manual about it, since it is certain to confuse some.

**Comment by gitjeff2** [comment]
> I think using '£' is better than redefining the bitmap btw - since that is what is printed on keyboards.

Yes, I agree with you. You're welcome to use my explanation text in the manual if you want. :-)

**Comment by darkstar** [comment]
It's actually not that unusual to have a different glyph on the code point 0x5c that we here know as `\`. Japanese DOS and Windows PCs, for example, have the "Yen" Glyph (¥) on that code point, that's why there all path names look like `C:¥Windows¥System32` etc. Korean and other east-asian locales are similar.

So there's probably no real reason to change anything, `£` should be fine

**Comment by polluks** [comment]
Just for the records:
"No conversion also means the the line comment word \ is entered and shown as the English Pound Sterling, aka GBP, sign, _ is backarrow, and ^ is up arrow. On the command line, any character from $00 to space is treated as whitespace, as is any character from $80 to Non-Break-Space ($A0)."
https://www.commanderx16.com/forum/index.php?/files/file/67-alpha-xforth-compiler/
