### ISSUE TITLE
Missing $ before a in format.fs?

### ISSUE THREAD

**Issue by burnsauce** [jkotlinski/durexforth#264]
When building format.fs from source, the interpreter fails on this line:

https://github.com/jkotlinski/durexforth/blob/3d666f96954d474beaf06d1441ae4466ccb612c0/forth_src/format.fs#L13

not recognizing the word 'a'.
I can only imagine that it's supposed to be a hex constant.  Is that correct?

**Comment by jkotlinski** [comment]
Hi! You are right - the $ is missing!

**Comment by burnsauce** [comment]
This begs a question for me: how are the files successfully compiled into the base dictionary?  I confess, I can't follow the build process.

**Comment by Whammo** [comment]
Something like this?
compile.fs

---modules---
marker ---modules---
include labels
include doloop
include format
include sys
include debug
include ls
include require
marker ---editor---
include v
save-forth @0:durexforth

**Comment by burnsauce** [comment]
That's what I was looking for, thanks!  Couldn't see the forest for the trees after a week of data entry :)

**Comment by burnsauce** [comment]
Now I see that format.fs is interpreted while hex is enforced, so this is not a bug.
