### ISSUE TITLE
When is tail call elimination compiled?

### ISSUE THREAD

**Issue by burnsauce** [jkotlinski/durexforth#266]
After
`---editor---
include v`
There is 1 difference in the compiled dictionary: the word `cursor-scr-pos` ends with `jp( + )` where the included editor has `+ exit`.

2 questions:

1. I can't find a code change that would cause this difference.  What code governs the application of tail call elimination (if that's what this is)?
2. Is there any problem with a `jmp` to `+`?

**Comment by Whammo** [comment]
The word SEE looks at things a little differently.

**Comment by burnsauce** [comment]
I'm doing apples to apples here. Decompiling the word reveals that yes, the binary version has a JSR and an RTS and the built-from-source version has a JMP.

**Comment by Whammo** [comment]
It seems one needs to recompile to benefit from tail call elimination.

**Comment by burnsauce** [comment]
That's a possible answer that begs the technical answer to question 1.

**Comment by Whammo** [comment]
I don't quite have my head wrapped around:

 https://github.com/jkotlinski/durexforth/blob/master/compiler.asm

**Comment by burnsauce** [comment]
I'm in a situation now where this question is begging my attention.  Consider this:
```
$1234 value somevector
: dovector state @ if somevector compile, 
else somevector execute then ; immediate
```
The idea here is that when encountered in the compile state, `dovector` will compile a jump to `somevector` in its current state.  If `somevector` changes, the compiled word would not change.
```
: foo ;
' foo to somevector
: bar dovector ;
: bar2 foo ;
ok
see bar see bar2
: bar foo exit ;
: bar2 jp( foo ) ;
```
The direct call to `foo` in `bar2` benefits from tail call elimination, but the vectorized `compile,` call to the same word does not.

**Comment by jkotlinski** [comment]
Hi, sorry for the late reply.
As a rule of thumb, TCO is applied conservatively not to break anything.
I am fairly sure that right now, anything IMMEDIATE disables TCO.
This should of course be properly documented.

**Comment by burnsauce** [comment]
Reading through the code I find your assertions true.  The relevant section of code I was not seeing was `EXIT` in control.asm, where the JMP/JSR decision is made.  Thanks!
