### ISSUE TITLE
Turtle word LS masks module LS

### ISSUE THREAD

**Issue by burnsauce** [jkotlinski/durexforth#267]
https://github.com/jkotlinski/durexforth/blob/76f18fd7267e5ed68574a3b0eff1d498733e5036/forth_src/turtle.fs#L8

**Comment by Whammo** [comment]
Very cool. It's fun to poke around in dusty corners.  :)

**Comment by Whammo** [comment]
Perhaps 7LS and 7RS could be the replacements.

**Comment by burnsauce** [comment]
It's irrelevant now, actually. Private words like this can be stripped from the word list.  I'll have a commit for turtle.ls soon.

**Comment by Whammo** [comment]
Nice!

**Comment by jkotlinski** [comment]
stripped!
