### ISSUE TITLE
Shrinking V

### ISSUE THREAD

**Issue by burnsauce** [jkotlinski/durexforth#268]
I have 2 ideas for shrinking the size of V, both of which presume that the names of the internal words are unimportant and disposable.  If this assumption is not in keeping with project goals, I'll abandon the effort.

1. Perform source-file translation of `v.fs` (at build time) to shrink the size of dictionary text entries. 
2. Use `:noname` to remove all internal words from the dictionary

Which approach should I take?  1 is easy but nasty, polluting the dictionary with meaningless words, without very much space saving.  2 would save a lot more space and keep the dictionary clean, but `v.fs` will become more complex.

**Comment by gitjeff2** [comment]
There are a few other projects that have expressed interest in porting *V* to other Forth implementations on other CPU architectures. The [CollapseOS](https://collapseos.org/) crowd comes to mind. They're starting with their own Z80 Forth and going 8/16-bit cross platform from there.

Hypothetically, could *V* be shrunk in such a way as to increase its portability across architectures? I haven't had time to dig into it myself.

**Comment by burnsauce** [comment]
The 2 option would not be portable beyond 6502 and the threading model used in durexforth, as it would involve directly assembling JSR instructions.

**Comment by jkotlinski** [comment]
One idea that crossed my mind would be having some other dictionary structure, that allows for temporary dictionaries that can be discarded when no longer needed. Of course, it would be some work setting that up.

**Comment by burnsauce** [comment]
You mean like this?
```
latest @ $a000 !
here $a002 !
$a004 to here
: splice $a000 @ $a002 @ ! ;
\ build some compile-time helpers
$a002 @ to here

\ write code that uses helpers OUTSIDE of the compile state
splice
```

**Comment by burnsauce** [comment]
Ah, I have the full, clean solution!  Using the above to hide compile-time words, I added the words (without looking at the standard, no doubt non-compliant) `DEFER` and `IS` where `DEFER` spits out a `JSR,` of the contents of the data field.

Nonaming can now be completed entirely at word definition, no further source changes required.  The result is a clean dictionary with nothing but a smaller `V`, where the source file remains readable.  If this is an acceptable strategy, I'll do the legwork then send in a PR.

**Comment by jkotlinski** [comment]
What I had in mind was to put the dictionary in its own memory space, so that it has it's own HERE and LATEST pointers.
This means word headers would be completely separate from code and data.

Doing this has some advantages

- when doing "turnkey" applications, the dictionary can be stripped away entirely for a smaller binary
- after compiling V, all word headers can be discarded, except the ones that are necessary for using the application

**Comment by burnsauce** [comment]
To the meat of this issue: should I continue with a custom solution for `V`?  It's a major percentage of the "internal" words in the binary distribution.  There are ~850 bytes to be gained there, but only a handful before `---editor---` that are not required to be interpreted.

I like the broad approach of a separate dictionary, but it's a long row to hoe compared to hacking `V`, IMO.  Then again, I didn't architect durexforth ;)

**Comment by jkotlinski** [comment]
It depends a bit what your motivation is. If you need those bytes urgently
to do something, by all means go ahead.
The problem of word headers wasting space is not unique to the editor
though, its equally a problem to the other modules. That’s why I think it
might be better to try to solve the problem on a higher level.

**Comment by burnsauce** [comment]
I was looking to push a shrink patch upstream so that I could work on expanding the editor without bumping the cart limit.  If you're going to rework the wordlist for the next release then shrinking V exclusively would never see the light of day, I suppose.

I'll just work on expanding the editor for now and submit PRs once the cart can support it.  Closing this issue.
