### ISSUE TITLE
Shrinking dictionary

### ISSUE THREAD

**Issue by polluks** [jkotlinski/durexforth#269]
Something like this https://stackoverflow.com/a/38104617/1430535

**Comment by burnsauce** [comment]
There's a project that does this as a cross-compiler: https://github.com/jkotlinski/acmeforth

Natively, I don't think some of those improvements apply to durexforth core, as it has to be interpreted.

**Comment by polluks** [comment]
I see, thx.

**Comment by burnsauce** [comment]
@polluks looks like this issue is indeed valid!

**Comment by burnsauce** [comment]
I created 2 incompatible pull requests as ideas for moving forward.  The latest is my attempt to remove the dictionary from data space.  This will permit the stripping of the dictionary for turn-key deployment.  It also saves 2 bytes per word ;)

**Comment by burnsauce** [comment]
Now that the dictionary headers have been split from the code, the potential exists to shrink the space used by the headers.  Several options exist now:

- `SAVE-PRG` strips all headers from the saved PRG file, already implemented.
- `HIDE` has been floated to remove individual word headers, easily implemented with `MOVE`.
- `HIDE:`, `;HIDE`, and `SHOW` ( or perhaps `MODULE:`, `;MODULE`, `EXPORT` ) for bulk hiding with selective export.  Example:

```
header foo
hide:
: bar ;
: baz ;
:noname bar baz ; show foo
;hide
```

`bar` and `baz` headers don't appear in the final dictionary, and `foo` is assigned the XT of the `:noname`.

Experiments show that judicious use of these reduction techniques leaves over 500 bytes free on the cart build, currently more than 300 bytes in deficit.

**Comment by jkotlinski** [comment]
How about e.g.

    defer myword
    latest
    : bar ;
    : baz ;
    :noname bar baz ; is myword
    to latest

? then no new words need to be added and I think it's easy to understand.

**Comment by burnsauce** [comment]
That works! Defer isn't in the base distribution, though.

**Comment by jkotlinski** [comment]
I think it is fine, it could be added first thing after `---modules---` master perhaps, then it does not affect minimum strippable size and can be used for the modules.

**Comment by burnsauce** [comment]
Looks like that works out well.  PR submitted.  Now it's just down to stripping the words that aren't required.  Many that I thought would not be are actually useful in `SEE`, e.g.: `(OF)`, etc. so I don't really know what's fair game, like `lstk` etc.

`V` can be stripped of almost everything except `V`, `BUFSTART`, and...?

**Comment by jkotlinski** [comment]
I'm not sure... probably it does not make sense to go overboard and strip absolutely everything, but for the modules, I think a good rule of thumb can be to expose those words that are mentioned in the documentation and strip the rest. If that somehow proves to be too much, maybe rather the documentation should be expanded :-)

**Comment by burnsauce** [comment]
Hmmm... a limitation of `defer` as a means of exposing public words has arisen: `immediate`.

You can't `immediate` a `noname` and it doesn't make sense (I think) to `immediate` a deferred word.

I think we will need a `header` / `defines` strategy (modifying the XT in the dictionary).

**Comment by jkotlinski** [comment]
Its fine trying different stuff, however, wouldn’t ’defer foo immediate’
work just fine?
Maybe i’m missing something again :-)

**Comment by burnsauce** [comment]
Nah, it's me that's missing stuff again. :)  That would work just fine.

**Comment by burnsauce** [comment]
Either way, hiding a bunch of words immediately following a deferred word really messes up `see`.  One fix would be to shortcut the `dodoes` as a marker for the end of a word.  Would that mess anything else up?

**Comment by burnsauce** [comment]
I can't imagine anything else that can be done at this point.  The dictionary has been shrunk and tools exist to shrink it further.

**Comment by jkotlinski** [comment]
happy to close @polluks or other things to be considered still?

**Comment by jkotlinski** [comment]
I hereby declare this to be a tremendous success, and close the issue.
