### ISSUE TITLE
Factor Kernal swapping to SYS

### ISSUE THREAD

**Issue by burnsauce** [jkotlinski/durexforth#288]
`rom-kernal` of `gfx` and `kernal-in` of `v` are similar, as are their counterparts.

It seems like these words should be factored into `sys` or somewhere.

**Comment by Whammo** [comment]
Perhaps this is a non-issue.
I can do like:
```forth
code bank
w       sta,
$01     lda,
$f8     and,#
w       ora,
$01     sta,
;code
```
And v
```forth
\ ram + io + kernal rom
code rom-kernal
$06 lda,# ' bank jsr, ;code
\ ram + io + ram
code ram-kernal
$05 lda,# ' bank jsr, ;code
```
And gfx
```forth
code kernal-in
6 lda,# ' bank jsr, cli, ;code
code kernal-out
sei, 5 lda,# ' bank jsr, ;code
```
 But it adds a couple bytes and it not something that should be done lightly.

**Comment by burnsauce** [comment]
I think this issue has been resolved: it's not worth the savings to factor these commonly.
