### ISSUE TITLE
Displaying Dictionary with RDIR

### ISSUE THREAD

**Issue by Whammo** [jkotlinski/durexforth#293]
If each Dictionary entry were 6 bytes followed by a null terminated string, and the last entry terminated by two nulls, It would display quite nicely, printing bytes 3 and 4 as blocks followed by the string.

**Comment by burnsauce** [comment]
You mean that by altering the dictionary header structure, it would display better on a memory dump?

**Comment by Whammo** [comment]
I appreciate you entertaining the notion. You're right of course.

**Comment by Whammo** [comment]
Not as much overhead per entry as I had supposed.

**Comment by burnsauce** [comment]
Current overhead is STRLEN + 3, FYI.  Couldn't be tighter. :)

**Comment by Whammo** [comment]
I totally get it- you'll find I'm generous with bad ideas.  :)

**Comment by burnsauce** [comment]
> I totally get it- you'll find I'm generous with bad ideas. :)

Hey, me too! :)

**Comment by jkotlinski** [comment]
You mean STRLEN + 2, right?

What could possibly be done further is to compress strings.
A common optimization is to not actually store all characters of the word. Then you store the string length + e.g. up to 8 first characters in a word. I did not find this optimization particularly valuable in practice, but it's an option.
Another option is to hash the word name using e.g. CRC-16. I don't like that it makes debugging harder, but it's possible and might speed up wordlist searches too.

**Comment by burnsauce** [comment]
STRLEN + 3: Count byte, String, XT.

**Comment by jkotlinski** [comment]
Ah, yes. XT is two bytes :)

**Comment by Whammo** [comment]
Interestingly enough, I have an implementation of CRC 16 in both forth and 6502 that I've used for PPP in the past.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jkotlinski** [comment]
Actually, biggest problem with hashing word names is that then WORDS won’t
work.

**Comment by Whammo** [comment]
Hmmmm, the wordlist and markers could be offloaded to disk. I wonder what else could be relegated to ‘virtual memory’?

**Comment by burnsauce** [comment]
Wordlist can't go on disk for the cartridge build :(

**Comment by jkotlinski** [comment]
Also - what about new words!

**Comment by Whammo** [comment]
Yes wordlist on disk is problematic for the cart build. Perhaps a better cart is on the horizon.

New words names would be appended to disk. In memory, the compliment of the checksum of the name of the new word and the likewise checksums of previous words names are appended to the list of checksums, each entry of which is an index to it's execution token.

To see if a word exists, init the CRC, calculate over the name, then calculate the list of checksums checking each for a good CRC. If you get to the end of the list without a match it's a new word.

**Comment by burnsauce** [comment]
Sounds like a job for the little-used REL file.

Also sounds like the cart forth kernel will diverge from the disk build somewhat.

You thinking about putting something like this together @Whammo?

**Comment by Whammo** [comment]
I'm certainly enjoying rolling it around in my head!
Collisions are a real though remote possibility too. I can't account for that yet.
This would also introduce the need for disk discipline and hygiene, shutting down properly and repair.
 Icky. 
 I had in the past considered replacing the unused load address in the .prg files with a CRC-16 checksum of the file, but never really explored the possibility.

**Comment by Whammo** [comment]
Not to beat a dead horse, but I did misspeak about the format of the RDIR. It's four bytes: line link word, blocks word, followed by the null terminated string.  Still an extra two bytes, even if it removes the need for length.
