### ISSUE TITLE
BYE does nothing useful

### ISSUE THREAD

**Issue by burnsauce** [jkotlinski/durexforth#298]
Currently, typing `bye` does not return the system to a functional state.

Is it possible to do so?  I'm not sure what's "broken" for BASIC.

**Comment by jkotlinski** [comment]
I’m pretty sure I had that working at some point.

**Comment by burnsauce** [comment]
A little testing shows that at a fresh boot, it works as expected.  I'll see if I can reproduce the bug.

**Comment by burnsauce** [comment]
Fresh boot -> bye
1. Wrong charset
2. Can't LOAD anything (see 1)
3. Immediate PRINT (see 1)

Switching the charset doesn't help, still interprets the character from other charset.

I feel like we might need to call a warm reset vector.

**Comment by burnsauce** [comment]
Calling warm reset vector is not enough.  =/

**Comment by Whammo** [comment]
: bye 64738 sys ;

**Comment by burnsauce** [comment]
Ah, that one works alright!

**Comment by burnsauce** [comment]
@jkotlinski put the kibosh on that vector.  I would have to guess that the actual source of the problem is in the zeropage.  I know BASIC relies on some stuff that gets trashed by the data stack.

**Comment by jkotlinski** [comment]
Confirmed that this used to work, but broke in commit 43915492725c794901dcb298e1301cbd1b230d66.

**Comment by jkotlinski** [comment]
Alternatively, the current BYE behavior could simply be documented and expected behavior.

**Comment by jkotlinski** [comment]
I had a quick stab at restoring zeropage, but no success, maybe restoring the zeropage area is not enough.
I am unsure what the best solution for this problem would be.
Maybe it would be better to leave `bye` undefined :-)

**Comment by burnsauce** [comment]
I'm for removing it until a reliable method with a convincing use case comes along.  Or throw it in compat.fs at least.

**Comment by Whammo** [comment]
I think the question is whether with BYE, DurexForth RTS's back to the machine language program that had JSR'd to it.
It looks to be this aspect works. 
It's obvious that basic is trashed, and it does return.

**Comment by Whammo** [comment]
If you change line 10 to:

10 sys2061:sys64738

You'll likely get what we're looking for. It works from immediate mode.

**Comment by Whammo** [comment]
However this would restart the cart.

**Comment by Whammo** [comment]
Here's what I have discovered:
 $e394 SYS works well when DurexForth is loaded from disk.
  64738 SYS works well when the cart is used, and does not restart the cart. ( at least in VICE)
  Disk operations and character sets are normal, and RUN starts DurexForth if basic is not disturbed.
   There is more at which to be looked, but at this point a cart Boolean makes sense.

**Comment by Whammo** [comment]
It's that the BASIC ROM isn't switched in.

**Comment by jkotlinski** [comment]
I tested ending `bye` with `jmp $e59a` instead of `rts`.
Sadly, `include test` followed by `bye` then `run` gives `?SYNTAX ERROR`.

Maybe it's practical best solution to simply discard current `bye`, and possibly put `: bye 64738 sys ;` in compat.fs

**Comment by Whammo** [comment]
I wasn't thinking of BYE as part of the standard. Maybe I should look at that first.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jkotlinski** [comment]
Standard simply says "Return control to the host operating system, if any."
