### ISSUE TITLE
Nested INCLUDEs

### ISSUE THREAD

**Issue by Whammo** [jkotlinski/durexforth#314]
It doesn't seem to want to go more than 3-4 deep. Is this a known issue? It makes sense.

**Comment by jkotlinski** [comment]
Yes, it’s known. It has to save a lot of state so I kept max depth fairly
low. Does it fail cleanly with an abort, or just cause real weird behavior
due to overwriting random memory? I don’t remember how I did it...

**Comment by Whammo** [comment]
Preliminary testing shows immediate mode fails cleanly with "no channel" dos message. From V, fails at same place with file open, no message.

**Comment by Whammo** [comment]
Easy to work around.

require gfx
require open
require io
require dos
marker foo
base @ hex

\ Doodle!

: doodle parse-name \ filename.dd
8 8 open ioabort
clrchn
8 chkin ioabort
chrin chrin 2drop
hires
400 0 do chrin colbase i + c! loop
2000 0 do chrin bmpbase i + c! loop
clrchn
8 close
key drop lores
;

base !

**Comment by jkotlinski** [comment]
I tested a little now and things are not working well anymore. Maybe
something went wrong with latest I/O changes.

I was thinking what’s missing is a check in SAVE _INPUT to prevent stack
overflow, but I can’t even get to that point.

**Comment by Whammo** [comment]
I'm still using v2 binaries.  FYI Nothing else seems to be at issue.  I've ported most of the dos, io and open to forth. It sure compiles faster.

**Comment by jkotlinski** [comment]
here is something weird that happens in master...

repro:

1. v a
2. insert ".( a) include b"
3. ZZ
4. include a
5. v b
6. insert ".( b) include c"
7. ZZ
8. include a

what happens: nothing
expected: after step 8, "ab" would be printed

**Comment by jkotlinski** [comment]
Seems related to something we recently discussed - seems fixed by 504ae17 , making QUIT close all open files.

@Whammo : Does your text editor allow use of [EditorConfig](https://editorconfig.org/) ? It could help keeping whitespace consistent.

**Comment by jkotlinski** [comment]
When trying nested includes now, I manage to open three files but the fourth fails with "70 NO CHANNEL". Docs say about this error message:
"The requested channel is not available, or all channels are in use. A maximum of five sequential files may be opened at one time to the DOS. Direct access channels may have six opened files."
So it sounds like it is failing a bit sooner than it should..?!

**Comment by jkotlinski** [comment]
I guess either it's working as expected now, or it's not :)  I'm not sure to be honest.

**Comment by Whammo** [comment]
I generally edit directly in Github, in my fork. It's definitely not WYSIWYG.

**Comment by Whammo** [comment]
This is the behavior that I reported.  It also seems that it counts keys and screen as files.
  The only fix I believe, would be to reverse queue the filenames and close the includes as we go and build the chain up then load and close the chain back down.
  This is a quite a bit of code and memory. Perhaps this is a limitation with which we can learn to live
