### ISSUE TITLE
Interpreter.asm restore_handler disallows RS-232

### ISSUE THREAD

**Issue by Whammo** [jkotlinski/durexforth#331]
$FE47 $318 ! allows RS-232 but introduces issues:

- restore is ineffectual, run/stop restore breaks DurexForth
- QUIT resets NMI vector

**Comment by AussieSmitty** [comment]
Hi Whammo,

After resolving an issue I was having with WinVICE I've come back to see if I can use RS232 from DurexForth. I tested that my setup works (i.e. using WinVICE and connecting a USB to RS232 cable to the destination [an Arduino]) works properly with basic, but in DurexForth I'm only getting some bytes and they are all around $ff and not all getting through.

Is there a new build of DurexForth with your fix? 

Thanks,
Steve

**Comment by Whammo** [comment]
The fixes I've offered have not been tested by me. It may also be that durexforth uses  zero page required for rs232.

 Otherwise, I am still pretty certain  $FE47 $318 !  is needed for rs232 and that QUIT changes it back.

**Comment by AussieSmitty** [comment]
Thanks Whammo,
While I do get something coming out of the RS232 after using $fe47 $318 !  I'm only getting $ff or $fe and sometime nothing, so perhaps your right and other parts of zero page are being used by DurexForth. I might re-write my code to not use any zero page (currently I'm using $fb and $fc which should be unused).
I will let you know of any progress.
Thanks,
Steve

**Comment by AussieSmitty** [comment]
Hi Whammo,
I stored my temporary bytes at $8000 and $8001 and still no joy. Same issue as above.
When using a machine code routine, have only been saving and restoring the x register. Do I need to also save and restore the a and y?
Thanks for your help as I appreciate this probably isn't a concern to most DurexForth users. My goal is to do robotics and hence I'd like to use RS232 2-way comms, and while I have this working in Assembler or Basic, my preference is to use Forth going forward.
Regards,
Steve

**Comment by Whammo** [comment]
You might check the output buffer to see if your bytes made it that far.

**Comment by Whammo** [comment]
BTW: You only need to save and restore X for CODE or [ , It's the parameter stack pointer. You can also skip using assembly with SYS calls, or even the new DOS/io/OPEN words that are yet to be in a release..

**Comment by Whammo** [comment]
It's supposed to.

**Comment by jkotlinski** [comment]
Is it working as supposed?
I did not mean to disallow RS-232. So if that’s the case, it’s clearly a
bug/shortcoming.

**Comment by Whammo** [comment]
Unless testing has gone awry, there is more at issue than the redirection of NMI's.
 I'm through working on this for the time being, so it's a non-issue to me.

**Comment by Whammo** [comment]
Once the code was sorted out, this makes it go.
 Restore drops through okay, but stop/restore might turn out badly.
```forth
$fe47 $318 !  \ default NMI vector
$fe $ce1 c! $47 $cdc c!  \  set quit_reset in interpreter.asm to point to default NMI vector 
```

**Comment by Whammo** [comment]
This is my best effort. I don't seem to have the Git skills to not introduce a bunch of noise into the codebase.

 This avoids rom cart init- passes through non-CIA NMI's (Restore) silently, and executes quit at run/stop Restore.
Replaces restore_handler entirely in interpreter.asm

```assembly
restore_handler
   cli
   pha				; save a
   txa				; copy x
   pha				; save x
   tya				; copy y
   pha				; save y
   lda	#$7f			; disable all interrupts
   sta	lab_dd0d		; 
   ldy	lab_dd0d		; save via 2 icr
   bpl stop_restore    ; if high bit not set

kernal_nmi
   jmp $fe72    		;.

stop_restore
   jsr	$f6bc		; increment real time clock
   jsr	$ffe1		; scan stop key
   bne	kernal_nmi	; if not [stop] restore registers and exit interrupt
   
   jmp QUIT    
```

**Comment by Whammo** [comment]
Something fun for brk. Save the registers to SYS: AR, XR, YR, SR, and put the software interrupt return address on the top of the data stack.

**Comment by Whammo** [comment]
#340  This resolves it.

**Comment by Whammo** [comment]
Depending upon what I'm doing, I'm getting bad stack effects on run/stop restore. 
  Is there a maximum stack depth we can check  if X > max then jmp abort?

**Comment by AussieSmitty** [comment]
Hi Whammo,

I also noticed that if I use LEAVE to get out of BEGIN AGAIN it not only leaves back to Forth, but drops out to the C64 start screen. I'm going to do some testing to confirm if this only occurs on the outer most loop, but any improvement you do for NMI handling would be appreciated in the DurexForth community.

Steve

**Comment by Whammo** [comment]
> Hi Whammo,
> 
> I also noticed that if I use LEAVE to get out of BEGIN AGAIN it not only leaves back to Forth, but drops out to the C64 start screen. I'm going to do some testing to confirm if this only occurs on the outer most loop, but any improvement you do for NMI handling would be appreciated in the DurexForth community, I'm sure.
> 
> Steve

 LEAVE is for DO LOOP, If you don't want an infinite BEGIN AGAIN loop to EXIT, I recommend using:
 
 begin ... until BEGIN loop-part condition UNTIL.
Loop until condition is true.
-or-

begin ... while ... repeat BEGIN condition WHILE loop-part REPEAT.
Repeat loop-part while condition is true.

**Comment by jkotlinski** [comment]
> Depending upon what I'm doing, I'm getting bad stack effects on run/stop restore.
> Is there a maximum stack depth we can check if X > max then jmp abort?

any repro for weirdness?
