### ISSUE TITLE
RS232 use affects disk access

### ISSUE THREAD

**Issue by AussieSmitty** [jkotlinski/durexforth#357]
There appears to be disk I/O issues after utilising RS232. Here is the code I use to set the RS232 port for 1200 baud.

( RS232 on C64 )

: setup ( -- ) 
14 53280 c! \ light blue border
154 emit    \ text colour
6 53281 c!  \ background dark blue
[ $fb stx,    \ store a copy of xreg
8 lda,#     \ low byte of params
$fd sta,    \ store at $fd
0 lda,#     \ hi byte of params
$fe sta,    \ store at $fe
$2 lda,#    \ length of filename
$fd ldx,#   \ lo byte params add
$0  ldy,#   \ hi byte params add
$ffbd jsr,  \ call kernal setnam
2 lda,#     \ 2 = RS232 device#
tax,        \ set device=2
0 ldy,#     \ no secondary #
$ffba jsr,  \ setlfs
$ffc0 
jsr,  \ open
$fb ldx, ]  \ restore xreg
147 emit ;  \ clear screen

Here is the routine I use to send a byte (which is working fine)

: sendbyte ( byte -- ) $fc c! [
$fb stx,    \ save xreg
2 ldx,#     \ rs232 device #
$ffc9 jsr,  \ chkout
$fc lda,    \ byte to send
$ffd2 jsr,  \ chrout
3 ldx,#     \ screen device #
$ffc9 jsr,  \ chkout
$fb ldx, ] ; \ restore xreg

I discovered after compiling (F7) the code above, and using it, e.g.:

setup
13 sendbyte

then go back to the editor (using 'v'), any change I then make to the code can't be saved.

Perhaps the issue lies in the way I am setting or using the RS232, but at this stage it appears to be that DurexForth's access to disk kernal is somehow affected by the use of RS232.

Thanks in advance for any help.
![Save not working](https://user-images.githubusercontent.com/41884798/129478160-e6dba638-176c-4a0a-b630-5538f609f188.PNG)

**Comment by Whammo** [comment]
May I suggest, you're not trapping for i/o errors i.e. checking for carry after kernal calls. Things may be in an 'undefined' state.
 If you would, try using the IO words and see if disk access is impared.

**Comment by AussieSmitty** [comment]
Hi Whammo,

Thanks for offering to assist.

I'm not sure what you're suggesting. Are you saying I need to call something first to check the status before I try to save to a disk?

Editing existing Forth code should allow a save, but as the image I captured shows, I'm not getting any disk activity (normally shown with a green light in the bottom right rectangle). Saving works until I use RS232, but not sure how to 'trap for i/o errors'. Thanks for further guidance on how to resolve this.

Regards,
Steve

**Comment by Whammo** [comment]
Device 2 is both input and output.

```forth
: sendbyte ( byte -- ) $fc c! [
$fb stx, \ save xreg
2 ldx,# \ rs232 device #
$ffc9 jsr, \ chkout
$fc lda, \ byte to send
$ffd2 jsr, \ chrout
3 ldx,# \ screen device #
$ffc9 jsr, \ chkout        <------     2 is still input
$fb ldx, ] 
clrchn ; \ restore xreg  <----- clrchn


```

**Comment by AussieSmitty** [comment]
Hi Whammo,

I think you've seen my error, thanks. I'll try it tonight and confirm you're genius status!

Steve

**Comment by Whammo** [comment]
I've been doing this for nearly forty years, It doesn't take a genius to understand it's not genius. 😉

**Comment by AussieSmitty** [comment]
Hi Whammo,

Still not working for me I'm afraid :(

I looked back as my working assembly code and I do the same as my Forth code. I did notice that I also called CLRCHN just to make sure the IO is clear. But even if I introduce this to my 'sendbyte' word, saving from the v editor again fails.

: sendbyte ( byte -- ) $fc c! [
$fb stx,    \ save xreg
2 ldx,#     \ rs232 device #
$ffc9 jsr,  \ chkout
$fc lda,    \ byte to send
$ffd2 jsr,  \ chrout
3 ldx,#     \ screen device #
$ffc9 jsr,  \ chkout
$ffcc jsr,  \ clrchn
0 ldx,      \ revert keyboard as input
$ffc9 jsr,  \ chkout
$ffcc jsr,  \ clrchn
$fb ldx, ] ; \ restore xreg

I feel like you are onto something, but I still can't get my head around where the issue lies. Perhaps I need to close the RS232 everytime I've sent a byte, but that I'm sure isn't supposed to be needed. I'm opening RS232 with a logical file number of 2 as well as device 2. Which means the v editor should still be able to open the disk channel for saving or reading as it would use a different logical file number.

I even tried using a different logical file number for rs232, but this made no difference.

Let me know if there is anything I can do to help as I'm keen to get this working for both RS232 and disk operations within my code.

Regards,
Steve

**Comment by jkotlinski** [comment]
I see an OPEN, but is the CLOSE missing, before you try to save to disk?

This advice was helpful to me, on how to order operations:
https://github.com/jkotlinski/durexforth/issues/95#issuecomment-748296717

**Comment by jkotlinski** [comment]
I think one problem can be found here:
https://github.com/jkotlinski/durexforth/blob/5c80c6e09639ccd76f3eb86ec0c19f0123a29cd8/disk.asm#L154
If I change this line to "lda #0", I can get things to work (whereas the original line does not)

I don't know WHY things go wrong, or what would be a good fix.
But I'm open for suggestions.

**Comment by Whammo** [comment]
Smitty, Is any disk access- for instance LS- disallowed, or is it only writing from V?

**Comment by jkotlinski** [comment]
It seems like SETUP LS wont work either.

**Comment by Whammo** [comment]
SETUP 8 DEVICE LS 

??

**Comment by AussieSmitty** [comment]
Hi Whammo & jkotlinski,

You've nailed it! :) If I do an 8 device, disk io for the directory or to save from the v editor now all works.

Thank you, now to my robotic projects with my C64 hardware and RS232 connections to external hardware.

Regards,
Steve

**Comment by jkotlinski** [comment]
Great! I guess theres still a problem to be solved, this setup seems error
prone when using multiple devices.

**Comment by Whammo** [comment]
The good part is that $ba is handled by the Kernal and should
always be the current (valid) device.
DEVICE should be it's own zeropage byte and let the Kernal handle $ba
 
 ```forth
disk_io_setnamsetlfs ;reused by both loadb and saveb
    jsr SETNAM
    lda $ba		;last used device number  <---  ldx device
    and #3		;Make 0-3 possible numbers     *snip*
    ora #8		;Transform to 8-B                        *snip*
    tax                                                                     *snip*
    lda #1
    ldy #0		;if load: 0 = load to new address, if save: 0 = dunno, but okay...
    jmp SETLFS	;End with JMP instead of jsr/rts to save a jsr/rts pair...
```

**Comment by Whammo** [comment]
Using $02 for DEVICE and the current release a preliminary patch:

```forth
8 2 c!        \ default device number to device
2 154e c!   \ DEVICE sta $02
2 155b c!   \ disk_io_setnamsetlfs lda $02
2 29a7 c!   \ open.fs $02 ldx,
```
These are the references (I have found) where the Kernal expects device to be disk and will update $ba

**Comment by jkotlinski** [comment]
that's food for thought.
I don't agree DEVICE should use a zeropage byte, zeropage is such a precious resource.

i'm wondering if it makes sense to let DEVICE be a plain VARIABLE, default value 8, which could then
be used by OPEN, LOADB and SAVEB, or any word that would like to use it.

to change device: e.g. "9 device !"

main drawback as i see it is, it would be a breaking change.

**Comment by Whammo** [comment]
There seems to be a little more to it than is implied by my patch.
 
 Setting $ba to 2, while device is 8 then executing LS returns 0,0, ok 0,0 but no directory. After that it works correctly.

**Comment by Whammo** [comment]
Hmmm..
If load_binary_laddr_hi = 0 then load_binary_status = fail and jsr	_errorchread
this catches a bad load address or 0 save filename length.

```asm
   lda $ba		;last used device number
    and #3		;Make 0-3 possible numbers
    ora #8		;Transform to 8-B
``` 
I don't understand why this happens, but 2 works out to $a

**Comment by Whammo** [comment]
I also notice .disk_io_setnamsetlfs calls SETNAM before SETLFS.

References say, call the SETLFS, and SETNAM routines and I can't seem to find another code example of SETNAM before SETLFS anywhere. Admittedly, I haven't tried very hard.

**Comment by jkotlinski** [comment]
The file loading was based on this code:

https://codebase64.org/doku.php?id=base:loading_a_file

**Comment by Whammo** [comment]
There are people that can solve this at a glance. I am assuredly not one of them.
It wouldn't be ruining my fun if somebody stepped up.
    greg-king5  ?

 Johan, I'm grateful for your time and attention and proud to have had a finger in the pie.
 Meanwhile, I'll enjoy exploring the implications of my patch.

**Comment by Whammo** [comment]
BTW, 
SETLFS, and SETNAM are incredibly simple routines that don't share zero page, it was obvious when I looked at the Kernal source that it matters not what order they're called.
 Heck, they're so simple, it might be worth loosing the overhead  and go directly from the data stack to zero page skipping the calls.

```asm
*****************************
FDF9 85 B7 STA $B7
FDFB 86 BB STX $BB
FDFD 84 BC STY $BC
FDFF 60 RTS
*****************************
FEOO 85 B8 STA $B8
FE02 86 BA STX $BA
FE04 84 B9 STY $B9
FE06 60 RTS
****************************
```

**Comment by Whammo** [comment]
So, DEVICE being irrelevant, INCLUDED shares _errorchread, knowing what we know now, we have the most excellent specifications below.
 Chuck Moore was correct about the power of 'code, then code again' with forth.
 This stuff practically writes itself.
```forth
LOADB ( filenameptr filenamelen dst -- endaddress ) load binary file
SAVEB (save binary file)
;  - 7000 71ae s" base" saveb #save file from 7000 to 71ae (= the byte AFTER the last byte in the file)
```

**Comment by Whammo** [comment]
But what I'm missing, without a doubt is that this is highly space optimized code, written by experts and that I am crunchy, and taste good with catsup.   😊

**Comment by polluks** [comment]
> SETLFS, and SETNAM

Kernal routines help porting to C128...

**Comment by Whammo** [comment]
```asm
+BACKLINK "device", 6
    lda LSB,x
    sta $ba
    inx
    rts

```
to

```asm
+BACKLINK "device", 6
    lda LSB,x
    sta device
    inx
    rts
device = * 
    php  ; $08
```
 Then point $ba writes to device.

**Comment by jkotlinski** [comment]
that code would not work straight off: because "device" assembler label cannot be accessed from Forth code.

it could also be that what's in place is actually good enough...

**Comment by Whammo** [comment]
Just for it to be documented, the (non)issue is reading $ba to subsequently set $ba with SETLFS, and:

```asm
.disk_io_setnamsetlfs ;reused by both loadb and saveb
    jsr SETNAM
    lda $ba		;last used device number
    and #3		;Make 0-3 possible numbers
    ora #8		;Transform to 8-B
    tax
    lda #1
    ldy #0		;if load: 0 = load to new address, if save: 0 = dunno, but okay...
    jmp SETLFS	;End with JMP instead of jsr/rts to save a jsr/rts pair...
```
.disk_io_setnamsetlfs transforming device $02 to $0a.

**Comment by jkotlinski** [comment]
I have an idea for improvement - thats not a breaking change or needs
further documentation:
LOADB and SAVEB could ABORT with error message if called with $ba outside
valid range.

**Comment by Whammo** [comment]
Any problem with vectoring Kernal LOAD & SAVE?

**Comment by jkotlinski** [comment]
How do you mean?
I check in to this thread too infrequently to follow any longer train of
thought ;)

**Comment by Whammo** [comment]
It might be worth flipping basic in and out to access the error messages at $a19e. the table is vectored by number @ $a328

**Comment by Whammo** [comment]
Here is a demo of basic error messages.
```forth
marker foo

: berr ( errornum -- )
55 1 c! 1-
1 lshift $a328 + @
begin dup c@ dup 128 and 0= while
emit 1+ repeat 128 - emit
drop 54 1 c! cr ;
```

**Comment by jkotlinski** [comment]
Since the reported problem is more or less solved now, I'm closing this to create specific follow-up issues.
