### ISSUE TITLE
Review LOADB+SAVEB error handling

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/durexforth#363]
Do LOADB+SAVEB have appropriate error handling? If not, fix it.

see discussion in #357

**Comment by Whammo** [comment]
LOADB has two modes of failure.
1. If the high byte of the destination address is zero, it still executes LOAD but sets load_binary_status to fail, executes _errorchread but zeropage could have been trashed.
 2. bcs .disk_io_error after LOAD also sets load_binary_status to fail,

**Comment by Whammo** [comment]
I'm pretty sure this works like it should.
 open.fs

```forth
marker foo
: setlfs ( file# sa -- )
$b9 c! $b8 c! ;

: setnam ( nameaddr namelen -- )
$b7 c! $bb ! ;

\ Open a logical file
\ ioresult is 0 on success, kernal
\ error # on failure.
( nameaddr namelen file# sa --
  ioresult )
: open
 setlfs setnam [ w stx,
$ffc0 jsr, \ OPEN
+branch bcs, \ carry set = error
0 lda,# \ A is only valid on error
:+
w ldx,
lsb sta,x
0 lda,# msb sta,x
] ;

\ Close a logical file
code close ( file# -- )
txa, pha,
lsb lda,x \ x = file#
$ffc3 jsr, \ CLOSE
pla, tax, inx,
;code

: errchk  sr c@ 1 and if
ar c@ else
0  then ;

: load  ( sa dst -- ioresult )
xr ! ar c! $ffd5 sys errchk ;

: save ( start end zeropage -- ioresult
)
dup ar c! swap xr ! !
$ffd8 sys errchk ;

( filenameptr filenamelen dst -- endadd
)
: loadb
1 0 setlfs -rot setnam 0
swap load drop $ae @ ;

: saveb ( start end nameaddr namelen --
)
1 0 setlfs setnam $c1 save drop ;
```

**Comment by jkotlinski** [comment]
Some thoughts about existing code:

 * I think it would be good if LOADB and SAVEB return an `ioresult` that can be checked by calling code. If one is too lazy to do proper error handling, at least it's easy to call `ioabort`
 * It might be more straightforward if LOADB returned the number of read bytes.
 * It's not so nice that LOADB and SAVEB assume that logical file# 1 is free to use. But it's maybe livable.

**Comment by jkotlinski** [comment]
i discovered now, CHKIN to device 0 (keyboard) actually does nothing! CHKIN may only be used for files!

**Comment by Whammo** [comment]
> Some thoughts about existing code:
> 
> * I think it would be good if LOADB and SAVEB return an `ioresult` that can be checked by calling code. If one is too lazy to do proper error handling, at least it's easy to call `ioabort`
> * It might be more straightforward if LOADB returned the number of read bytes.
> * It's not so nice that LOADB and SAVEB assume that logical file# 1 is free to use. But it's maybe livable.
> * It's not good that LOADB and SAVEB check the error channel in case of failure. If there is no device, it will hang.

 ioresult could be a variable that is simply overwritten with the next file, stack, or even a FIFO buffer

**Comment by jkotlinski** [comment]
yes, that could work too, with the advantage that it's not a breaking change.
benefits of returning `ioresult` is that it encourages error handling, and it is similar to standard word [READ-FILE](https://forth-standard.org/standard/file/READ-FILE).

**Comment by jkotlinski** [comment]
it's also a bit of open question if LOADB/SAVEB should be interactive or not.
the existing words are interactive, in that they read and print the command channel.
my gut feel is that the words are more generally useful if they are Not interactive, and instead return `ioresult`. but I think I could be convinced otherwise.

**Comment by jkotlinski** [comment]
...I think I change my mind! I now think it's fine if LOADB/SAVEB keep their current signatures, and are "interactive"
but they should be improved so that they always give some nice feedback to user, and never hang or lock up

**Comment by jkotlinski** [comment]
Problems to fix:

- [ ] `12 device parse-name foo $7000 loadb` hangs

**Comment by Whammo** [comment]
ST is supposed to set a timeout show serial bus timeout with Bit 2. I am unaware of the conditions, but it's something to look into.

**Comment by Whammo** [comment]
Load/Save uses fast loaders, so that's not going anywhere. so merely opening channel 15 first, then you can readst, and see if the device is present first. abort or close and then load/save.

**Comment by jkotlinski** [comment]
Oh! I forgot about fastloaders. But don’t they also follow the regular
pattern with returning status by carry flag + accumulator?
In that case, LOAD failure could be detected and handled before trying to
read error channel.

**Comment by Whammo** [comment]
The point is, LOAD blocks on a device not present error, right? So you can't check, the carry, it hangs.
 So if you can open an arbitrary file or the command channel first, you don't have to read it, but you know the device exists.
 Then you can safely LOAD

**Comment by Whammo** [comment]
Anyway, _errorchread definitely hangs if DEVICE not present. 

```forth
: ecr $1551 sys ; ( Version 3 address of _errorchread )
```
 Try it with different device numbers.

**Comment by jkotlinski** [comment]
I find that  LOAD does in fact return an error in A:

```
( set filename 'x' )
'x' w c!
1 ar ! w xr ! 0 yr !
$ffbd sys ( setnam )

( logical file 1
  device 10 - non existing
  secondary address 1 )
1 ar ! 10 xr ! 1 yr !
$ffba sys ( setlfs )

( LOAD file to memory )
0 ar ! $ffd5 sys

( prints 5 - DEVICE NOT PRESENT error )
cr
ar c@ .
```

**Comment by Whammo** [comment]
I was meaning LOADB and SAVEB hangs, no way to check status.

**Comment by jkotlinski** [comment]
Oh yes! I’d like to see that fixed

**Comment by jkotlinski** [comment]
It was complicated to fix `loadb` and `saveb` for every kind of error, so I'm abandoning this effort for now.

I follow your suggestion to let v check for a good device number: 9a4e8ce

**Comment by jkotlinski** [comment]
Created follow-up issue for the loadb/saveb hangs.

https://github.com/jkotlinski/durexforth/issues/499
