### ISSUE TITLE
bug: 'v v' wipes wordlist

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/durexforth#366]
Repro:

```
v v
:q 
words
```

What happens: `words?`

Expected: wordlist is printed

**Comment by jkotlinski** [comment]
it's unclear how to solve this in a good way.

**Comment by Whammo** [comment]
Is it so large that it overwrites the wordlist?

**Comment by jkotlinski** [comment]
I suppose so.

**Comment by Whammo** [comment]
It might be tricky, but there has been a suggestion to move the wordlist to the 4K RAM under i/o.

**Comment by jkotlinski** [comment]
Related: #311

**Comment by Whammo** [comment]
Yes it does.
  $cbff TOP! v v
 
 good stuff

**Comment by jkotlinski** [comment]
A good solution for this would be to rewrite "v" so that it does not use unbounded memory. However that is a pretty big undertaking.

**Comment by jkotlinski** [comment]
Actually! There is a solid way to solve this problem, without much work at all.

Before v actually loads a file, read the disk directory to see how big it is (in blocks, each block holding 254 bytes). If the file is too big for the buffer, `ABORT" too big"`.

**Comment by jkotlinski** [comment]
https://github.com/jkotlinski/durexforth/pull/395

^ this seems to work. sadly, there's not room on the cartridge (yet)

**Comment by jkotlinski** [comment]
A related thing now. Editor text buffer sits very awkwardly. It starts at $7000, and gets squeezed between HERE (grows up) and LATEST (grows down). 
Wouldn't it make sense to move it to $a000-$cbff ?
