### ISSUE TITLE
Link to Transactor Volume 7 Issue 5 broken

### ISSUE THREAD

**Issue by pgeorgi** [jkotlinski/durexforth#367]
The link at 

https://github.com/jkotlinski/durexforth/blob/115f6dc9efae9518b27efe7bf5f6c07ea75b5efd/docs/tutorial.tex#L198

is broken and even the internet archive doesn't have a working copy of the page. Instead, maybe point to https://archive.org/details/transactor-magazines-v7-i05/page/n59/mode/2up?

**Comment by jkotlinski** [comment]
Fixed, thank you for reporting!
