### ISSUE TITLE
v doesn't handle long page well

### ISSUE THREAD

**Issue by ChristopherDrum** [jkotlinski/durexforth#373]
If I start writing word definitions and I get to the end of one screen of text, I can write additional lines and the page scrolls as expected. However, coming back to edit the screen results in what appears to be an off-by-one error, where the cursor appears to be on one line, but is actually editing the previous line.

Beginning an edit then draws the actual text being edited in line with the cursor. So we now see two lines of the same text. Here I was trying to delete the extraneous `:w` on the last line. When I hit backspace to delete the w, the `;:w` line jumped down one line, the previous `sextal #...` line displayed on the cursor line, which caused me to delete the `s` on that line instead, but the `sextal...` line still shows as being in the line above the cursor. In fact every line in this screenshot is displaying one line higher than the editing cursor believes.

![image](https://user-images.githubusercontent.com/320377/139082376-cc9410f9-f1df-4f61-bade-0cad82bf8631.png)

I'm unclear how to precisely reproduce the issue, but will investigate it more thoroughly.

**Comment by jkotlinski** [comment]
Hi!
That sounds quite annoying.
Please let me know if you find any specific ways to repro.
Thanks for the report!

**Comment by jkotlinski** [comment]
When trying to reproduce, I noticed that inserting SHIFT+RETURN will make the editor behave really weirdly. Could that be it?

**Comment by jkotlinski** [comment]
Overall, "weird" characters in the buffer are not handled well. Maybe there should be some whitelist for what can be displayed on screen.
