### ISSUE TITLE
IOABORT not usable for device 2

### ISSUE THREAD

**Issue by Whammo** [jkotlinski/durexforth#407]
: rs232_open 2 device 6 here c! here 1 5 5 open ;
 . . 5 240 
 
device 2 is go on 240
device 2 is no-go on 0
 
   ERROR RETURNS : ERROR NUMBER IN .A IF CARRY IS SET ON RETURN
    0      Terminated by STOP key     :  5      Device not present error
    1      Too many open files error  :  6      Not an input file       
    2      File open error            :  7      Not an output file      
    3      File not open error        :  8      File name error         
    4      File not found error       :  9      Illegal device error    
    240    RS-232 buffer allocated/de-allocated (top of BASIC memory moved)

**Comment by Whammo** [comment]
Perhaps rs232 support should be a module? It would allow: trimming down interpreter.asm markedly, and exploring the integration of other NMI routines.

**Comment by jkotlinski** [comment]
Trying `#240 ioabort` in master, it aborts with error message `ioerr`. Seems like OK behavior to me.

"top of BASIC memory moved" when/how does that even happen?

**Comment by Whammo** [comment]
One needs to open device two before allocating variables in basic because the Kernal moves top of memory down two pages to make room for the ring buffers.

**Comment by Whammo** [comment]
It shouldn't abort- it's a successful open. It's okay to catch these 'errors' yourself, but it complicates the code.

**Comment by jkotlinski** [comment]
ok... but we don't allocate variables in basic? i'm a bit confused how it could happen in Forth use case.

**Comment by Whammo** [comment]
This is the Kernal loading 240 and Jumping to settop whose rts is the end of open 2


```asm
F47E   A9 F0      LDA #$F0
F480   4C 2D FE   JMP $FE2D
```
It's pretty much just their work around using the BASIC mechanism to place the buffers in memory. It doesn't disturb memory, 
It has no relevance in the forth context,  I just set the pointers myself.

```forth

$a100 $f7 ! $a200 $f9 ! \ buffer pointers


```

**Comment by Whammo** [comment]
I believe it boils down to IOABORT not checking carry. 
Only abort if carry set.

**Comment by Whammo** [comment]
Open 2 returns 240 in a and carry clear if successful. Carry set and error number in a otherwise.

**Comment by Whammo** [comment]
So, open does check carry, The point is, device 2 errors are different and a little wonky.
 Open and close 2 use 'errors' to report state changes, in the manner of 'this-level-up' , 'this-level-down'. 'this-level-start' and 'this-level-stop'. 
 There are multiple states between carry, a returns and and contents of ST, handshaking lines and etc.
  Devices other than 2 are much simpler.

**Comment by Whammo** [comment]
Device 2 s supposed to be the physical layer of the OSI or some older model and operates within a state machine.

**Comment by jkotlinski** [comment]
I don't get it. Looking at the code for Durexforth `open`, it does inspect carry?

```$ffc0 jsr, \ OPEN
+branch bcs, \ carry set = error
0 lda,# \ A is only valid on error
:+
w ldx,
inx, inx, inx,
lsb sta,x
0 lda,# msb sta,x
;code```

[docs ](https://www.pagetable.com/c64ref/kernal/#OPEN) also say: `The carry will be clear if the file was successfully opened, or it will be set if it could not be opened. When carry is set upon return, the accumulator will hold an error code indicating the problem.`

**Comment by jkotlinski** [comment]
...ok. so you are saying, in the case of RS-232 it signals an error but it does not really mean error?

That's a bit weird. I guess one could add a special case for that in OPEN, but it is not appealing.

I'm not opposed to adding an optional RS-232 module.

**Comment by Whammo** [comment]
$ffc0 jsr, \ OPEN
+branch **_bcs,_** \ carry set = error
0 lda,# \ A is only valid on error
:+

**Comment by Whammo** [comment]
There are events, actions and a State Transition Table. Depending upon the state, different actions are available and events can happen and these transition the state, etc.

**Comment by jkotlinski** [comment]
Hmm... Isn't [this](http://unusedino.de/ec64/technical/aay/c64/romf409.htm) the relevant code?

If $FA (RS232 output buffer pointer) is not set, OPEN will fail with the error $F0.
So it indeed seems like $F0 is a valid error, that indicates that OPEN fails because the output buffer has not been initialized.

**Comment by jkotlinski** [comment]
Actually, I misread it a bit.

Docs write about $F9-FA: "Pointer to RS232 output buffer
    $00-$FF: No buffer defined, a new buffer must be allocated upon RS232 output.
    $0100-$FFFF: Buffer pointer."

So if I understand right. OPEN checks if a buffer pointer has been already allocated. If not, it allocates a buffer. If it has already been allocated, it fails with the $F0 error?

**Comment by jkotlinski** [comment]
(in short: IOABORT and OPEN works correctly, and $f0 is a real error?)

**Comment by Whammo** [comment]
Not if it has $F0 in a, carry set AND 0 in ST.

```asm
F47D: 38        SEC
F47E: A9 F0     LDA #$F0
F480: 4C 2D FE  JMP $FE2D     ; Read / Set Top of Memory
\ and
F453: AD 01 DD  LDA $DD01     ; CIA2: Data Port B (User Port, RS232)
F456: 0A        ASL
F457: B0 03     BCS $F45C
F459: 20 0D F0  JSR $F00D 

F00D   A9 40      LDA #$40
\ to
F00F   8D 97 02   STA $0297	; RSSTAT - RS-232: Mock 6551 Status Register
F012   18         CLC
F013   60         RTS
 
``

**Comment by jkotlinski** [comment]
That is so strange, but I guess it is just the way it is!

**Comment by Whammo** [comment]
Sorry, there are some discrepancies with that source.

```asm
F459 20 0D F0 JSR $F00D | JMP CKDSRX      ;NO DATA SET...DSR ERROR EXIT;
```
I'm going off of my experiences trying things. I may be looking at the code from the wrong perspective.
 If you want to close this until I get something working and can demonstrate something, I'm all for that.

**Comment by Whammo** [comment]
https://www.floodgap.com/retrobits/ckb/display.cgi?124

**Comment by jkotlinski** [comment]
I like that sentence 

    "It looks like a lot of code compared to a simple 
    OPEN 8,8,8,"testfile" like you would use from BASIC, and it is. But once 
    you have done it one time and have an assembler source file with it then 
    it is a simple matter to re-use that code in another program. After 
    writing just a few small programs in assembly language you can build a 
    library of routines that you will use over and over again, and thus make 
    the job easier as you gain experience. "

I guess question is, is a new set of routines needed, or are the ones that already exist in Durexforth good enough.

**Comment by jkotlinski** [comment]
One thing that cannot hurt either way, is documentation or examples how to do RS-232 programming.

**Comment by Whammo** [comment]
It is possible to open files with contradictory or ambiguous settings and the kernal will just roll with it, using whatever happens to be in memory at the time. Hence, you can use the same bad settings at different times and get different results, without crashing or throwing an error.

**Comment by Whammo** [comment]
At some point I'm going to propose this change in part for the rs232 module.
Much smaller and making Forth-friendly jumps into the CIA 2 NMI ignoring restore handler possible.

```asm
restore_handler     ; this becomes OLD-VECTOR
    jmp QUIT        ; all NMI and brk instructions go here
quit_reset          
    sei             ; goes here for QUIT , program start        
    lda #<restore_handler
    sta $318        ; nmi vector
    sta $316        ; brk vector
    lda #>restore_handler
    sta $319         ; nmi vector
    sta $317         ; brk vector
    
    cli              ; OLD_VECTOR +16
```
in lieu of

```asm
restore_handler
   pha				; save a
   txa				; copy x
   pha				; save x
   tya				; copy y
   pha				; save y
   lda	#$7f	    ; disable all CIA 2 interrupts
   sta	$dd0d       ;
   ldy	$dd0d       ; save CIA 2 interrupt control register for kernal_nmi
   bpl brk_handler  ; CIA 2 is not the NMI source if the most significant bit is not set.

kernal_nmi
   jmp $fe72        ; all CIA 2 NMI's fall through to the Kernals' RS-232 routines
   
                    
brk_handler         ; all non-CIA NMI (RESTORE key) and brk instructions- via IRQ vector end up here.
    pla             ; drop y -the return stack will be reset by QUIT anyway
    pla             ; pull x
    tax             ; restore parameter stack pointer for QUIT
    jmp QUIT        ; already under sei from NMI stub in Kernal or from IRQ to brk_handler
    
quit_reset
    sei             ; goes here from QUIT and program start
    
    lda #<restore_handler
    sta $318
    lda #>restore_handler
    sta $319

    lda #<brk_handler
    sta $316
    lda #>brk_handler
    sta $317

    cli ; still have to
```
And ultimately, making this possible!
```forth
318 @ value old-vector


code nmi
here        pha,
            txa,
            pha,
            tya,
            pha,
$7f         lda,#
$dd0d       sta,
$dd0d       ldy,
+branch     bpl,

$fe72       jmp,

here swap               \ +branch to tos         
:+          pla,
            pla,
            tax,
            sei,
                        \ quit_reset
swap dup 100/
swap $ff and

            lda,#       \ restore
$318        sta,
            lda,#
$319        sta,

dup 100/ swap
$ff and
 
            lda,#       \ brk
$316        sta,
            lda,#
$317        sta,

$10 old-vector +
             jsr        \ quit-reset
' quit 3 +   jmp        \ reset return stack and interpret             
;code

: install ' nmi $318 ! [ $318 (jmp), ] ;
```

**Comment by Whammo** [comment]
We have rs232 with durexForth. 3.0.0.

![vice-screen-20220110012048](https://user-images.githubusercontent.com/38296423/148743165-0890de76-bca9-4b60-8c8f-a70ee68ec312.jpg)

**Comment by Whammo** [comment]
It doesn't require integration into the system to work, so unless there is a specification or a request for such, I'm satisfied this is resolved.
