### ISSUE TITLE
Idea: Double Literals and M*/

### ISSUE THREAD

**Issue by burnsauce** [jkotlinski/durexforth#433]
Some forths feature double literals via a trailing period, e.g.: `40000.` , `-1234567.`

While double literals themselves are not that big a feature, they require implementation of `m*/` to operate.  From the standard:

> M*/ was once described by Chuck Moore as the most useful arithmetic operator in Forth. It is the main workhorse in most computations involving double-cell numbers.

It's the only operator that multiplies with a double as an input.

Should these be added to Durexforth?

**Comment by jkotlinski** [comment]
What is the use case?
Personally I never had much of a desire to use double numbers.

**Comment by burnsauce** [comment]
> Fixed point math would benefit greatly from M*/

The single-precision divisor limits fractional components to 14-bits, as, say fractional multiply requires `f1 * f2 / 1 << fbits`.  As we cannot divide by a signed $8000 we must set the fractional component at 14 to divide by $4000.

Therefore, `M*/` offers no great automatic advantage in fractional math for multiplication.  I will continue to explore this space.
