### ISSUE TITLE
Space after filename or before drive status upon save in V slipped

### ISSUE THREAD

**Issue by Whammo** [jkotlinski/durexforth#457]
saving boo00, ok,00,00

![save-v](https://user-images.githubusercontent.com/38296423/182751402-5662bb12-66bc-4261-b6f4-77bbaba09051.gif)

**Comment by jkotlinski** [comment]
problem appeared with b5cd7201685eda8702f7d30347616a692519242d

**Comment by Whammo** [comment]
I think this may be because ```v``` enables Kernal logging before saving, then calls ioabort which uses BASIC logging.
```forth
rom-kernal
page
$9d c@ $ff $9d c! \ kernal log on

\ scratch old file
here
's' over c! 1+
'0' over c! 1+
':' over c! 1+
filename 1+ over filename c@ move
filename c@ + lf swap c!
here filename c@ 4 +
$f $f open ioabort $f close
```

**Comment by Whammo** [comment]
Leading space before ' ok' is normal. though it's the only message that supplies one.

**Comment by Whammo** [comment]
```v``` is large enough. Perhaps in ```saveb``` disk.asm
```forth
    
    jsr SAVE
    lda $20     ;here
    jsr CHROUT  ;to here
    jsr _errorchread
```

**Comment by jkotlinski** [comment]
yes... probably it also makes sense if SAVEB enables & resets kernal logging instead of WRITE-FILE?

**Comment by Whammo** [comment]
That bell is whistling clearly now. 😃
