### ISSUE TITLE
Document contributors

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/durexforth#460]
I think it would make sense to clearly document who contributed to this project.

**Comment by jkotlinski** [comment]
@Whammo I am working on this task a bit. Updating license texts and so on.

Would you like to be mentioned? Can/should I add your real name?

**Comment by Whammo** [comment]
Sure, Kevin Lee Reno and/or Whammo is fine.
 
  Wow, it's been like ten years since I submitted ```ls```

**Comment by jkotlinski** [comment]
OK, great, thank you!

Time flies like an arrow!

**Comment by jkotlinski** [comment]
Duplicate of #223
