### ISSUE TITLE
Errors in durexforth.asm

### ISSUE THREAD

**Issue by GooseDeveloper** [jkotlinski/durexforth#469]
After installing [acme](https://github.com/meonwax/acme) and running `make all`:
```
Error - File durexforth.asm, line 120 (Zone <untitled>): There's more than one character.
Error - File durexforth.asm, line 120 (Zone <untitled>): No value given.
Error - File durexforth.asm, line 120 (Zone <untitled>): Macro not defined (or wrong signature).
Error - File durexforth.asm, line 103 (Macro BACKLINK): Unknown function.
Error - File durexforth.asm, line 103 (Macro BACKLINK): No value given.
Serious error - File durexforth.asm, line 105 (Macro BACKLINK): Value not defined (__LATEST).
```
I'd love to try out forth on a Commodore 64, but I don't have a real one :(

Thanks!

OS: Linux
Distro: Ubuntu
Desktop: GNOME
Arch: x86 64

**Comment by jkotlinski** [comment]
Hi!
Could it be that you are not running the most recent ACME version? There
has been breaking changes lately. I should make it clear in the source,
which is the minimum required version.
I usually use emulator, too.

**Comment by GooseDeveloper** [comment]
Output of `acme --version`:
```
This is ACME, release 0.96.4 ("Fenchurch"), 1 Feb 2019
  Platform independent version.
```

**Comment by jkotlinski** [comment]
Upgrading to 0.97 will fix the problem!

**Comment by GooseDeveloper** [comment]
> Upgrading to 0.97 will fix the problem!

The Sourceforge version doesn't support Linux and the one linked in the original question seems to be out of date

**Comment by GooseDeveloper** [comment]
> Upgrading to 0.97 will fix the problem!

I believe compiling from source should fix the issue...

**Comment by jkotlinski** [comment]
Yes that should be fine!
