### ISSUE TITLE
Quotation marks in PDF

### ISSUE THREAD

**Issue by polluks** [jkotlinski/durexforth#484]
Just a minor thing, always typographical close quotation marks are used.

**Comment by jkotlinski** [comment]
Is it a problem of the old LaTeX PDF, or the new Asciidoc generated PDF?

**Comment by polluks** [comment]
It was already in 3.0.

**Comment by jkotlinski** [comment]
For better or worse, asciidoctor-pdf generates straight quotation marks. So
it seems like this issue is already resolved.

**Comment by polluks** [comment]
Indeed?
<img width="212" alt="quote" src="https://user-images.githubusercontent.com/4707573/194764548-3f31ebbb-f883-481e-b1b3-c0856e74053b.png">

**Comment by jkotlinski** [comment]
asciidoc-pdf, which is used in master branch "make deploy", generates PDF output like this:

![bild](https://user-images.githubusercontent.com/3259963/194768272-fc4f3bfd-ec52-4b96-b99f-b5696dc14e92.png)

**Comment by polluks** [comment]
I see, it's not the same like https://github.com/jkotlinski/durexforth/releases/download/v4.0.0/durexforth-v4_0_0.pdf.
