### ISSUE TITLE
Support control characters in editor

### ISSUE THREAD

**Issue by IanWitham** [jkotlinski/durexforth#492]
The screen editor in immediate mode can take advantage of PETSCII control characters in strings, e.g. left cursor, home, reverse on/off.

The vi editor doesn't seem to allow entering control characters. Is this a feature you could add?

**Comment by jkotlinski** [comment]
Entering control characters was disabled because of bugs.
For it to work correctly, I think a ”string mode” would be needed, with
special rules for entering and displaying control characters.
The interpreter has this for free, since it reuses input logic from the
BASIC interpreter.
I do not know if it is possible to reuse that logic in the editor.
Maybe it would be easier if it was a line editor.

**Comment by IanWitham** [comment]
From a user's perspective, a special "string insert mode" would be ideal.

**Comment by jkotlinski** [comment]
Makes sense!
Maybe it’s real easy to just escape the control chars to something else, so
they can be displayed on-screen.

**Comment by jkotlinski** [comment]
I think I got it figured out in master.
Do you have possibility to make a new durexForth build and try it out?

**Comment by IanWitham** [comment]
I'll give it a try, thanks.

**Comment by IanWitham** [comment]
When I run the build I get the attached message in Vice.
![vice-screen-2022121920401818](https://user-images.githubusercontent.com/1018548/208372880-35d5ee02-5b26-4883-9857-697ce50b3214.png)

**Comment by polluks** [comment]
Me too

**Comment by IanWitham** [comment]
This error seems to prevent the .crt and .d64 files from being produced, but I can at least test the v editor from this screen while the "make" build is stalled. The control characters are working fine in this build. :-)

**Comment by jkotlinski** [comment]
Oops, that sounds like an ASCII-to-PETSCII conversion error. Thanks for
testing!

**Comment by jkotlinski** [comment]
Investigated a bit, apparently the ”aa” error was because the Makefile was
not written in a portable manner. It should be fixed now. Cheers!

**Comment by IanWitham** [comment]
Working great now! Thanks.

https://user-images.githubusercontent.com/1018548/208598600-42362afe-67f9-4141-80ba-53d586aa9a15.mp4
