### ISSUE TITLE
Cursor keys not working in v

### ISSUE THREAD

**Issue by IanWitham** [jkotlinski/durexforth#496]
While in edit mode, cursor keys inside a string produce PETSCII control characters as expected from the recent commit. However, outside of a string they do nothing (i.e. the cursor doesn't move). 

The cursor keys still work while not in edit mode.

**Comment by jkotlinski** [comment]
I changed that intentionally. The reason was that it felt weird with a
behavior change from movement to insert as the cursor moved to a string.

Maybe there is a better way to do it, not sure.

**Comment by jkotlinski** [comment]
ok, should be working more or less ideally now.
