### ISSUE TITLE
REQUIRED stops working after 16 includes

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/durexforth#504]
It would make more sense if REQUIRED used a linked list, so that an unlimited number of includes is possible.

**Comment by Whammo** [comment]
Very cool. 👍

**Comment by jkotlinski** [comment]
Thank you, I got the linked list idea from forth-standard.org. 

Using a 16-bit string hash is a bit of a gamble. With an ideal 16-bit string hash function, there is a 1% risk of hash collision with 40 strings.
