### ISSUE TITLE
REFILL regression

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/durexforth#505]
Seems something broke with a9482fe9260049e8f19bf4220f9d34e63b82d5fa.

### repro

1. start `v`
2. insert `include io .( a)`
3. press F7

###  what happens

io module is loaded, but nothing is printed on screen

### expected

the letter `a` is printed on screen

**Comment by Whammo** [comment]
Somehow, I think this is related to the issue I had with V when replacing LOADB and SAVEB with their forth equivalents.

**Comment by jkotlinski** [comment]
This took a while to figure out. I hope it fixes your problem!

**Comment by Whammo** [comment]
I can't make sense of that stuff yet. I need more bigger screens!

**Comment by jkotlinski** [comment]
when trying to make a test case for this, I found another bug :-(
