### ISSUE TITLE
Ensure i/o is banked in before resetting screen memory in Interpreter.asm

### ISSUE THREAD

**Issue by Whammo** [jkotlinski/durexforth#540]
Nods to ekipan. #538

**Comment by ekipan** [comment]
Johan actually [already commited this](https://github.com/jkotlinski/durexforth/commit/1cba87a5cf1eaaa7526303cf19ed9851a4110d60) a few hours after I posted my comment.

**Comment by Whammo** [comment]
He's good like that.
