### ISSUE TITLE
`v`: support ctrl-[

### ISSUE THREAD

**Issue by ekipan** [jkotlinski/durexforth#544]
In PC terminal emulators `ctrl-[` sends the same keycode as `Esc`, `$1b`, so you can exit vi's insert mode without having to reach up for the escape key. DurexForth's `key` (and so presumably the C64 routines it uses) gives the same keycode so it could be nice for `v` to support for VICE users where `[` is unshifted. If I understand correctly the relevant source is [v.fs line 300](https://github.com/jkotlinski/durexforth/blob/485e245f4c56b6894ac3e8e762b1ba7efad85b5f/forth/v.fs#L300).

**Comment by polluks** [comment]
Indeed, cc65 supports this too https://cc65.github.io/doc/c64.html#ss9.1

**Comment by jkotlinski** [comment]
If it is a problem of VICE keyboard ergonomics, why not just change the VICE keyboard mapping so that it suits you better? It is eminently configurable.

**Comment by ekipan** [comment]
It's not any more ergonomic to press `Ctrl-[` vs. the default `Shift-~` for `<-`. Just another keystroke to share in common with vi, if you care about that. I'm not too concerned myself, wouldn't bother me if it were closed rejected. 

I'd be curious to know how many vi users even know this is possible.

**Comment by jkotlinski** [comment]
OK.... Well, I do not think there is enough RAM to add even 1% of vi keypresses, so so far, I try to stick to the essentials (at least for me), maybe it is already too much.

I had no idea about Ctrl+[ , I will try to remember that one and use it in everyday life. Thank you for the tip!

**Comment by ekipan** [comment]
It might [rely on an American English](https://vim.fandom.com/wiki/Avoid_the_escape_key) keyboard layout? Just FYI.
