### ISSUE TITLE
`\` broken when compiling from `v`

### ISSUE THREAD

**Issue by ekipan** [jkotlinski/durexforth#545]
Using the [latest build](https://github.com/jkotlinski/durexforth/actions/runs/4713236155) cartridge, pasting the following program into `v` and pressing `F7` won't compile the `bar` word.
```forth
: foo ;
\ test
: bar ;
```
The standard says [`\` discards](https://forth-standard.org/standard/core/bs) the rest of the parse area, so if I understand correctly that `v` compiles with `evaluate` then `\` comments no longer work.

Maybe it's rude to piggyback but an unrelated issue: the program `( test )` leaves 2 junk values on the stack. Looks like you need a `2drop` in the [definiton of `(`](https://github.com/jkotlinski/durexforth/blob/485e245f4c56b6894ac3e8e762b1ba7efad85b5f/forth/base.fs#L28).

**Comment by ekipan** [comment]
IMHO this seems like a problem with the standard that makes evaluate less useful. Seems there was [some discussion](https://forth-standard.org/standard/core/EVALUATE#contribution-217).

**Comment by jkotlinski** [comment]
> ( test ) leaves 2 junk values 

Thanks, nice catch, I made the fix as suggested!

I will have to look into fixing `v` too, obviously `evaluate` is no longer the right tool for the job.

**Comment by jkotlinski** [comment]
Hopefully it will be relatively useful again after c09c3c91957aa6beae928dc8fb80fd5db54197da , by which v F7 calls EVALUATE line-by-line.

**Comment by ekipan** [comment]
Looks fixed to me :+1:. Nice work and thanks.

I still think the standard should fix this problem with `\` though. I wonder how many programs out there depend on its current interaction with `evaluate`?

**Comment by ekipan** [comment]
Maybe I spoke too soon. 
```forth
: xx  [ :- iny,
-branch bne, ] ;
```
Pasting and F7'ing this program doesn't compile `xx`, it gives what looks like a "word not found" error with random looking text, perhaps from outside the buffer? It compiles if you `J`oin the lines together. Probably it can be reduced further, not sure of the cause.

**Comment by jkotlinski** [comment]
Should be fixed in 05eded9e30bfde1681b5c72ccdaa36c4932d6a90 . Very luxorious with debugging help, thank you :-)

**Comment by ekipan** [comment]
Untested off-the-cuff:
```forth
variable scan-base
: scan-line-or-quit ( -- addr u )
scan-base @ dup begin dup c@ case
 0 of 2drop quit endof
lf of dup 1+ scan-base ! over - exit 
endof endcase 1+ again ;

: main-loop
\ ...
\ f7
dup $88 = if 2drop cleanup rom-kernal
bufstart scan-base ! begin
scan-line-or-quit evaluate again then
\ ...
```

**Comment by jkotlinski** [comment]
That r> program would crash most Forths very hard :-)
It cannot be expected to work.

mån 17 apr. 2023 kl. 15:52 skrev ekipan ***@***.***>:

**Comment by ekipan** [comment]
> 3.2.3.3 
>
> [...] A system may use the return stack in an implementation-dependent manner during the compilation of definitions, [etc ...]

So I guess even with `>r` the above program would be considered environmentally-dependent.

**Comment by ekipan** [comment]
I've thought some more and realized my `scan-line-or-quit` is essentially the same as your `evaluate-buffer` just with:
1. `quit` and `evaluate` swapped places (not really useful)
2. `1+` moved inwards and thus duplicated (needed because of point 1?), and
3. saving its temporary in a variable instead of the rstack.

Point 3 means it supports more programs but if I understand the standard isn't strictly required.

**Comment by jkotlinski** [comment]
The standard says that `r>` `>r` interpreter behavior is undefined. There is no reason to expect that they would work in the interpreter.

**Comment by ekipan** [comment]
Implementation-defined*, not undefined. DurexForth may choose whether or not to support such programs and still be standard. 

Again, if I understand correctly. So yes the bug is fixed in terms of standard requirements.

**Comment by jkotlinski** [comment]
The exact standard phrasing for these words is: "Interpretation semantics for this word are undefined." So, in contrast to implementation-defined, it really means all bets are off and you might expect it to crash. There are good technical reasons for why it would crash, too.

That v F7 did not crash was more or less by accident, and making it crash, will in fact make it behave more like the interpreter. I see that as a good thing.

**Comment by ekipan** [comment]
```forth
.( a)
(
.( b)
.( c)
```
In `v` v4 F7ing this program prints `ac`, with this bugfix it prints `abc`.

**Comment by jkotlinski** [comment]
It is not a great behavior, but it is as expected. `(` is only supposed to grab multiple lines when parsing from a text file.

**Comment by ekipan** [comment]
>asm base float gfx labels open see sin sys timer

These files on disk contain multi-line `(` comments, as well as viceutil with a multiline `.(` use, though gfx does have some wide lines that `v` would truncate. I assumed `v`s F7 was intended to behave like `included` so one could experiment with and compile files on disk. Maybe that assumption was wrong. That's how I've been using it.

**Comment by ekipan** [comment]
Yeah. A little sad though, it's a convenient feature.

**Comment by jkotlinski** [comment]
If you miss it enough, you could create a new issue ”v F7 does not support
multi-line comments”. I cannot promise a fix though, it is a difficult
problem.

tis 2 maj 2023 kl. 23:04 skrev ekipan ***@***.***>:

**Comment by jkotlinski** [comment]
I do not think there is anything wrong with `\`. I think the fundamental shortcoming is that `EVALUATE` does not handle multi-line strings well. It looks like this shortcoming is also recognized within the wider Forth community.

If a fix for this problem is needed, it would be to switch back to a non-standard `EVALUATE` which handles multi-line strings well.

**Comment by jkotlinski** [comment]
Also: With a block-based text editor, this would not be a problem, as it would use LOAD rather than EVALUATE.

**Comment by ekipan** [comment]
[`\` already _is_ specified](https://forth-standard.org/standard/block/bs) to skip ahead an implementation-defined [block line length](https://forth-standard.org/standard/block#subsubsection.7.4.1.1) when `blk` is not 0, so this wouldn't be a problem even if `load` were implemented with `evaluate`. When `blk` is 0 then `\` should skip to the end-of-line as defined by `included` and I don't understand why you would disagree.

**Comment by jkotlinski** [comment]
Are you referring to the discussion at forth-standard.org , in the `(` comment section? That came out really weird. It looks like I am replying to your comment, but it had not been published yet when I wrote my reply - my reply was directed to Anton.

**Comment by jkotlinski** [comment]
To answer your proposal.

> When blk is 0 then \ should skip to the [end-of-line as defined by included](https://forth-standard.org/standard/file/INCLUDED) and I don't understand why you would disagree.

I agree that this is a desired end result. However, since this is a general problem, I would like to solve it in a way that helps more words than just `\`.

For example, imagine this particular naive `\` implementation: `: \ REFILL ;` It would be nice if also such words worked well with `v F7`.

**Comment by ekipan** [comment]
> Are you referring to the discussion at forth-standard.org

No, I was directly replying to your previous comment. How about this:

```forth
: file\ $d parse 2drop ;
: block\ ( round up >in to next block line ) ;
: \ blk @ if block\ else file\ then ; immediate
```

You can't use `refill` since that may change the input source, and when used in a block [is specified to get the next block](https://forth-standard.org/standard/block/REFILL).

> since this is a general problem, I would like to solve it in a way that helps more words than just `\`.

Other than `\ included read-line` does the standard define any words that care about lines?

**Comment by jkotlinski** [comment]
Sure, it is very likely that I have the wrong idea, it happened many times before. It does not seem smart to try to unify `REFILL`, given the difference between Blocks and Files.

Assuming that it is only a problem of `\`. I suppose the needed change is: "If SOURCE-ID is -1,  parse and discard the portion of the parse area corresponding to the remainder of the current line" ?

**Comment by jkotlinski** [comment]
reopening as the solution does not seem satisfactory.

**Comment by ekipan** [comment]
IMO it should probably just do it regardless of SOURCE-ID. At the keyboard or from an INCLUDED file there's only one line anyway so it doesn't matter. That leaves EVALUATE and LOAD. The [BLOCK-extended \\](https://forth-standard.org/standard/block/bs) says that if BLK is not zero \ should "discard the remainder of the line," where I think that's defined by the [line length here](https://forth-standard.org/standard/block#subsubsection.7.4.1.1), I say there should be a FILE-extended \ that does `$d parse 2drop` in the case of durexForth, presumably parsing until the line-terminator described by READ-LINE, if that differs for a different Forth.

**Comment by ekipan** [comment]
Attempting previously to compile z from within v left me in a bad state with an unresponsive interpreter but the [latest fix](https://github.com/jkotlinski/durexforth/actions/runs/4896895294) seems to compile it correctly.

**Comment by ekipan** [comment]
I found one edge case:
```forth
.( a)
\
.( b)
.( c)
```
No space after the `\`, in v4 this gives "abc" but with the fix gives "ac". I'm personally willing to not care about this edge case though.

**Comment by jkotlinski** [comment]
That seems very wrong though.

**Comment by Whammo** [comment]
Long lines are tricky. The line link table is mysterious.

**Comment by ekipan** [comment]
Hrrmnm perhaps this?
`: \ -1 >in +! $d parse drop drop ;`
Is there any possibility this could underflow the input buffer?

**Comment by jkotlinski** [comment]
I do not think there is anything wrong with the proposed `\` definition, but it seems like maybe something is wrong with `PARSE`.

**Comment by jkotlinski** [comment]
OK, I understand now what is going on.

> `: \ -1 >in +! $d parse drop drop ;`

That looks like a bit of a hack. What if `: x 0 >in ! postpone \ ;` ? OK, it is not super likely that someone would write code like that, but at the same time, there is no reason that it should cause undefined behavior.

**Comment by ekipan** [comment]
`: \ >in @ 1- 0 max >in ! $d parse drop drop ;`
This is definitely more subtle than I initially thought.

**Comment by jkotlinski** [comment]
I am not a fan of that `\` definition. I think I changed my mind back now. I am quoting Mitch Bradley, who designed the Forth input system:

"[...] the standard specifies an input model that is intended to be strictly line-oriented - the input buffer contains exactly one line."

"[...] reading the entire file into one big buffer is certainly feasible - I do that myself in some scenarios - but to be compliant with the standard as I understand it, REFILL needs to look for the next line delimiter and arrange for the input buffer to contain just the one line."

So... I now again think it makes sense to change `REFILL` and `(` to properly deal with multi-line `EVALUATE` strings. `REFILL` should split up the `EVALUATE` string line-by-line. `(` should work just like for text files.

**Comment by jkotlinski** [comment]
I have a better idea, which may be the standard-compatible and nice way to go about it.

Add a word `INCLUDE-RAM ( addr u -- )` which behaves pretty much like `INCLUDE`. It will set `SOURCE-ID` to a virtual file which is mapped to RAM. `REFILL` will include functionality to grab lines from that virtual file. End of story!

**Comment by jkotlinski** [comment]
I am toying now with the idea to make a creating word for defining custom refill behavior...

e.g. `-2 REFILLER ... ;` would define the behavior when `REFILL` gets an input line and `SOURCE-ID` is -2. The created code would have the signature `( -- FALSE | C-ADDR U )`; it should either return `FALSE` or the next line of the input source.

To include the custom -2 input source, one would call `-2 INCLUDE-FILE`.

With that, it would be possible to create a custom `REFILL` behavior specifically for including text files placed in a large RAM buffer.

I am also tempted to just hardcode a new `INCLUDE-RAM` method, maybe that is less work.

**Comment by jkotlinski** [comment]
Adding `INCLUDE-RAM` was not a lot of fuss at all. https://github.com/jkotlinski/durexforth/pull/556
