### ISSUE TITLE
`v`: can't cursor past the end of a line

### ISSUE THREAD

**Issue by ekipan** [jkotlinski/durexforth#552]
Try opening a file in `v` then press `A [left] [right]`. In v4 the cursor moves back onto the end, in v5-preview the cursor stops at the character before the newline.

_Originally posted by @ekipan in https://github.com/jkotlinski/durexforth/discussions/548#discussioncomment-5731443_

One bad effect is that you can't erase the last character in insert mode. You have to press `[<-] l x`.

**Comment by jkotlinski** [comment]
So the behavior changed between f255fef64b78e1a6d9b06eb6ac53dee181498332 and 09762542c2ed33950a2e9c786a07e36126a0d3a6. I am not sure how it used to work.

**Comment by ekipan** [comment]
Just to make it easier to see the range in github: f255fef64b78e1a6d9b06eb6ac53dee181498332...09762542c2ed33950a2e9c786a07e36126a0d3a6.
Thanks for the fix, I'll give it a try and report again if I find any more issues.
