### ISSUE TITLE
Nested `included` broken?

### ISSUE THREAD

**Issue by ekipan** [jkotlinski/durexforth#558]
Using the [latest build](https://github.com/jkotlinski/durexforth/actions/runs/4982988156). Files test1 and test2:
```forth
.( test1 )
1
include test2
dup + .
```
```forth
.( test2 )
```
Interpreter session (brackets mean inverted text):
```forth
durexForth
parse-name test1 included
test1 test2 [up?]
```

**Comment by ekipan** [comment]
Hrmm. Went back to durexForth v4 and it still was bugged.

I recently reconfigured VICE to use a host file system device. I changed it back to True Drive Emulation and put these two files on a disk image and it worked correctly. Possibly a VICE bug? Weird that I hadn't run into it before, I've been using host drive device for a week now.

**Comment by ekipan** [comment]
VICE's host filesystem device is super convenient, but also behaves a bit bizarrely. Any time I try to load a file in `v` it prints `file not found` and then seems to load it correctly anyway.

**Comment by ekipan** [comment]
I wonder if the JiffyDOS ROM could also be related?

**Comment by jkotlinski** [comment]
I don’t know, but I had problems recently  that only disappeared when I
disabled ”handle true drive emulation at autostart”, if i remember
correctly.

ons 17 maj 2023 kl. 05:02 skrev ekipan ***@***.***>:
