### ISSUE TITLE
not all demos load

### ISSUE THREAD

**Issue by thomas-villagers** [jkotlinski/durexforth#567]
Hi! 

some demos won't load: 

![Bildschirmfoto von 2023-08-04 08-30-48](https://github.com/jkotlinski/durexforth/assets/1818737/7abf62e9-bab0-4622-bb6d-4a8d6b778788)

Is this an emulator issue? Tested with v4 and v5 preview.

**Comment by jkotlinski** [comment]
Hi! It is likely an emulator issue. Please try different options for your
drive settings.

fre 4 aug. 2023 kl. 08:33 skrev thomas ***@***.***>:

**Comment by Whammo** [comment]
Enable  "True Drive Emulation"

**Comment by thomas-villagers** [comment]
Great, thank you -- this was it: I had to select Drive type 1541-II. :-)
