### ISSUE TITLE
Easy Flash support

### ISSUE THREAD

**Issue by wkjagt** [jkotlinski/durexforth#568]
I was hoping to use durexforth on my C64 with Easy Flash 3, but when I try to load the .crt file onto my Easy Flash 3, I get the following error:

![telegram-cloud-photo-size-1-5129780725434920045-y](https://github.com/jkotlinski/durexforth/assets/327048/b15aeb16-9b0d-4025-94ac-0c95b0b8ddc2)

Easy Flash 3 supports the following CRT types:

- Normal 8k and Normal 16k
- Ultimax
- Ocean Type 1
- EasyFlash and EasyFlash xbank.

I am not too familiar with the different types of cartridges, or with crt files, but going by [this](https://codebase64.org/doku.php?id=base:crt_file_format), looking at durexforth's crt file, it's using type 4 (Simon's Basic), which is not supported by Easy Flash. 

Is there a known way to build durexforth in a way that it works as a cartridge with Easy Flash?

**Comment by jkotlinski** [comment]
You could try using the cartconv utility that comes with Vice to change to
whatever cartridge type you prefer.
I haven’t tried lately, but I think there is a decent chance that default
.crt works fine. IIRC Simons’ is not essential, it’s just nice for freeing
some extra RAM.

ons 23 aug. 2023 kl. 22:25 skrev Willem van der Jagt <
***@***.***>:

**Comment by wkjagt** [comment]
Sounds like a good idea. Thanks for the pointer! I just tried but it doesn't want to convert from a one `crt` to another `crt`. It says `Error: File is already .crt format`. I'll look into a bit more, maybe there's a way.

**Comment by polluks** [comment]
You have to use build/cart.bin as input.

2023-08-23 23:12 GMT+02:00, Willem van der Jagt ***@***.***>:

**Comment by wkjagt** [comment]
Oh right! I could have seen that in the Makefile :-) Sorry! 

GOOD NEWS: I am able to build `master` successfully, and create a cartridge using `cartconv` and the cartridge works on my C64 using Easy Flash! Thank you!

However, I wanted to build v4.0.0 instead of the v5.0.0 preview, and I couldn't build that. I got the following errors:

1. When building the documentation, it pauses at the following, seemingly waiting for my input:

```
[Loading MPS to PDF converter (version 2006.09.02).]
)
(/usr/local/texlive/2022basic/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.s
ty
(/usr/local/texlive/2022basic/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg
)) [1 <./cover/durexForth-Vintage1.jpg>] (./release_license.tex (./params-g.tex

! Missing control sequence inserted.
<inserted text>
                \inaccessible
l.2 e
     visiontagdoc{v4.0.0.0.ga23afc7}
?
```
I can press enter a couple of times and it continues, but eventually stops with an error `!  ==> Fatal error occurred, no output PDF file produced!`

2. When removing the lines from the Makefile that create the docs (so I can continue to get the crt file), the build continues, but hangs in Vice at the following point:

<img width="726" alt="image" src="https://github.com/jkotlinski/durexforth/assets/327048/91deda0c-9b67-4593-b217-4d389b5aea37">

I get a blinking cursor in Vice, and I am in durexforth. The build doesn't continue here. It looks like it doesn't know the `aa` word. I haven't investigated any further.

**Comment by jkotlinski** [comment]
The ”aa” is probably some emulator issue. Try enabling true drive emulation.

Or, use cartconv to convert the .crt to .bin, and back to .crt with the
desired cartridge type.

tors 24 aug. 2023 kl. 01:14 skrev Willem van der Jagt <
***@***.***>:

**Comment by wkjagt** [comment]
> The ”aa” is probably some emulator issue. Try enabling true drive emulation.

I wonder if `aa` is from [here](https://github.com/jkotlinski/durexforth/blob/e20515ea8a38643084e8b4a83f419747128d46c4/Makefile#L48) .

> Or, use cartconv to convert the .crt to .bin, and back to .crt with the
> desired cartridge type.

Oh yeah, good idea, I'll try that
