### ISSUE TITLE
Can you compile forth programs to run without the forth environment?

### ISSUE THREAD

**Issue by Thraka** [jkotlinski/durexforth#571]

**Comment by burnsauce** [comment]
If you mean to never return to the interpreter and to shed the dictionary required for interactive use, yes!

Check the manual, section 2.7.3, Turn-key Operation

**Comment by Whammo** [comment]
It's a great manual.

**Comment by Thraka** [comment]
Sorry, I missed the original response. @burnsauce @Whammo What I mean is can you save to PRG, reset the machine to normal BASIC and run `LOAD"PROGRAM.PRG",8` and it runs?

**Comment by jkotlinski** [comment]
Yes, you should be able to do that following those instructions in the
manual.

ons 31 juli 2024 kl. 20:56 skrev Andy De George ***@***.***>:
