### ISSUE TITLE
>BODY is an unimplemented core word

### ISSUE THREAD

**Issue by WildKeccak** [jkotlinski/durexforth#572]
It's a core word in Forth 2012 

I would start with Starting Forth, Chapter 9.

I think it's at least somewhat important, if only for its inclusion in Starting Forth

**Comment by jkotlinski** [comment]
Hi!
It is implemented in compat.fs.
To load it, ”INCLUDE COMPAT”

All the best,
Johan

mån 27 maj 2024 kl. 04:25 skrev WildKeccak ***@***.***>:

**Comment by WildKeccak** [comment]
Thanks, I didn't think to include compat
