### ISSUE TITLE
LIT & LITC crazy slow

### ISSUE THREAD

**Issue by brucehoult** [jkotlinski/durexforth#578]
LIT and LITC are currently compiled as "jsr LIT; .word N" and "jsr LITC; .byte N".

The functions have to do a LOT of grovelling around to pop the return address from the stack and store it in W at the start and then bump W by 2 (LITC) or 3 (LIT) and jump to that address using self-modifying code.

First of all, I think it would be smaller and the same speed to add the constant to W in-place:

        clc
        lda W
        adc #3
        sta W
        bcc +
        inc W+1
    +   jmp (W)

That's 13 bytes vs 18 bytes 

BUT ... why not completely change it so LIT is compiled to "lda <N;ldy >N;jsr LIT" and LITC as "lda N;jsr LITC" ?

Then instead of the current 19 instructions LIT is simply:

    LIT
        dex
        sta LSB,x
        sty MSB,x
        rts

That is vastly simpler and faster, at a a cost of 1 extra byte of code for each LITC and 2 extra bytes of code for each LIT.

That feels like a good trade-off to me.

**Comment by jkotlinski** [comment]
Keeping LIT/LITC space optimized is a practical rather than philosophical
decision. For example, if you check gfxdemo.fs you will find a lot of
literals, and it does not matter if they are slow. So for code like that,
or most typical application code, I think its simply more beneficial to
optimize for size.

Subroutine threading is also practical, but in other ways. Actually I like
it most because it is simple and very easy to seamlessly mix Forth and
assembly words.

mån 2 dec. 2024 kl. 15:48 skrev Bruce Hoult ***@***.***>:

**Comment by ekipan** [comment]
FYI the routine `dex sta sty rts` does already have a name: `pushya`. `value`s jump to it.

I would maybe propose adding a third builtin number literal after 0 and 1: -1. It's kinda common plus a bunch of words in the core that currenly make and push flags could instead branch to 0 and -1.

**Comment by jkotlinski** [comment]
Adding -1 as a constant seems like a really good idea to me!

tis 3 dec. 2024 kl. 00:20 skrev ekipan ***@***.***>:

**Comment by jkotlinski** [comment]
Bruce, about the change you proposed:
”I think it would be smaller and the same speed to add the constant to W
in-place”

I agree this seems better! You are welcome to make a pull request!

tis 3 dec. 2024 kl. 10:55 skrev Johan Kotlinski ***@***.***>:

**Comment by ekipan** [comment]
If you have code with literals that needs fast you have a couple options.
```forth
\ values compile to lda ldy jmp.
\ maybe use prefix for multidigit 
\ to not step on other bases.
#1234 value #1234 

\ if you want to save 3 more
\ cycles you can compile inline:
: ]l ( n-;-n) ] split swap
  lda,# ldy,# ['] pushya jsr, ;

\ then replace 1 with 2:
: ex1 ( ... ) 1234 ( ... ) ;
: ex2 ( ... ) [ 1234 ]l ( ... ) ;
```

**Comment by jkotlinski** [comment]
I merged the optimized LIT and -1 now. Thanks for the suggestions!
