### ISSUE TITLE
`abort"` space savings, also github build problems

### ISSUE THREAD

**Issue by ekipan** [jkotlinski/durexforth#579]
`v.fs` uses `abort"` six times. Each time it compiles to:
```forth
if rvs s" ..." type cr abort then
```
I propose pulling a runtime factor, say, `aborts`:
```forth
: aborts ( au-) rvs type cr abort ;
: abort" ( -;f-) postpone if
postpone s" postpone aborts
postpone then ; immediate
```
Saving 4 bytes of code plus 9 bytes per use. Personally I think `aborts` is a more useful factor.
```forth
\ say I want to reset some state, I currently have to:
: ... ( ... ) is-bad? if reset-state 1 abort" bad" then ( ... ) ;
\ which is wasteful versus:
: ... ( ... ) is-bad? if reset-state s" bad" aborts then ( ... ) ;
````
Though introducing a new word does mean more documentation, so I wouldn't oppose `hide`ing it.

Edit: had `cr` in the wrong place.

**Comment by jkotlinski** [comment]
Sounds good to me!

tors 12 dec. 2024 kl. 23:16 skrev ekipan ***@***.***>:

**Comment by Whammo** [comment]
Ioabort has, for some time returned basic io error messages. This perhaps may have lessened the need for hard coded, disk error messages.

**Comment by Whammo** [comment]
Sorry, yeah I see they're internal messages.
 Heh. Never mind.

**Comment by ekipan** [comment]
I don't actually have a means to develop locally right now. Github does have a fancy in-browser vscode application that lets you directly develop on a github remote repo. When I synced my fork the build failed tho. Here's the output that differs on [your latest build](https://github.com/jkotlinski/durexforth/actions/runs/11922426001/job/33228648497#step:3:590) vs. [my build](https://github.com/ekipan/durexforth/actions/runs/12325292773/job/34404349370#step:3:590).

```
The following packages have unmet dependencies:
 headlessvice : Depends: libflac8 but it is not installable
```

I admit I don't really know what I'm doing. I could have done something wrong, or some remote software source might have linkrotted, breaking your next build as well?

**Comment by jkotlinski** [comment]
@ekipan I rebuilt the latest build, and it works for me. I don't know what I am doing either, so I do not see why it works for me but not you.

**Comment by jkotlinski** [comment]
@ekipan I bumped vice-headless dependency, does it make things any better for you?

**Comment by ekipan** [comment]
Failed again [trying to get libflac8](https://github.com/ekipan/durexforth/actions/runs/12327871753/job/34410400000#step:3:236), which is weird because I don't even see mention of it in your build log.

**Comment by jkotlinski** [comment]
It looks like your job has a newer runner version, using Ubuntu 24.04.1 LTS. Mine is still using 22.04.5 LTS.

**Comment by jkotlinski** [comment]
https://github.com/actions/runner-images/issues/10636

It appears that they have removed a bunch of packages.

What happens if you add "sudo apt install libflac8" before the headlessvice install?

**Comment by ekipan** [comment]
[Still no I'm afraid.](https://github.com/ekipan/durexforth/actions/runs/12328112101/job/34410900842#step:3:231)

So, this will eventually fail on your end too once Github rolls out the new version to you? 

The [VICE changelog](https://vice-emu.sourceforge.io/NEWS) mentions a `--without-flac` flag but I'm not sure how to use it. Probably have to do a manual build instead of `apt-get install *.deb`? I think I'll have to throw my hands up here.

**Comment by jkotlinski** [comment]
OK, I pinned Ubuntu 22.04 LTS. It should be fine for another two years. Meanwhile, I hope the problem is resolved on VICE side.
