### ISSUE TITLE
size opt: limit stored word name length

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jkotlinski/durexforth#60]
```
Names were compiled with a count and three characters, a practice learned
from the compiler writers of Stanford and which prevailed in Forth until
the 1980's.
http://www.forth.com/resources/evolution/evolve_0.html
```

Original issue reported on code.google.com by `kotlin...@gmail.com` on 18 Jan 2009 at 2:16

**Comment by jkotlinski** [comment]
not doing this right now, since there are practical benefits of keeping the full word name. and so far, no one reported practical problems due to running out of RAM
