### ISSUE TITLE
Cartridge version?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jkotlinski/durexforth#96]
```
Would free up some RAM
```

Original issue reported on code.google.com by `kotlin...@gmail.com` on 27 Oct 2012 at 11:59

**Comment by jkotlinski** [comment]
It would be great if editor and debug words are moved entirely to ROM.
It should still be possible to save custom Forths to disk, and execute the Forth images without the ROM.

**Comment by chitselb** [comment]
I'm contemplating a ROM version of http://github.com/chitselb/pettil but I'd be putting the core dictionary (minus assembler/editor/compiler/interpreter/symbols) in ROM at the $9000-$AFFF address space on the PET.  The development environment would be loaded into RAM, and user programs would have the entire $0400-$7FFF address space available

**Comment by jkotlinski** [comment]
this should theoretically be easy ; the practical problem now is that DurexForth takes more than 16 kbyte :P

**Comment by jkotlinski** [comment]
I guess this is in practice easily fixed by making the gfx package optional.

**Comment by jkotlinski** [comment]
OK. The next practical problem is that DurexForth uses BASIC getline in the interpreter. If DurexForth is 16 kByte, basic is switched out.

**Comment by jkotlinski** [comment]
One practical problem is that DurexForth relies the BASIC ROM, for example getting input in the interpreter. If BASIC ROM is left in, DurexForth has only 8 kByte ROM available. It would be very hard to fit it in. I tried stripping out gfx package and running exomizer - that only reduces the footprint to 10 kBytes.

**Comment by jkotlinski** [comment]
Keeping only core words in ROM would definitely be an option. But at the moment I don't see how that would benefit anyone.

**Comment by jkotlinski** [comment]
Probable next step: Drop all and any BASIC usage so that a 16 kB ROM can be made.

**Comment by jkotlinski** [comment]
Nice progress :)

Some issues still:
 * not possible to switch out $a000-$bfff now. move graphics to $d000.
 * restore key

**Comment by polluks** [comment]
You may switch out $a000-$bfff if you are running in $8000-$9fff, ok?

**Comment by jkotlinski** [comment]
It looks like it is not possible to switch out $a000-$bfff for 16 kB ROMs, without also switching out Kernal.

https://www.c64-wiki.com/index.php/Bank_Switching

Having said that. Maybe one option could be to copy Kernal to RAM, and run all RAM.

**Comment by jkotlinski** [comment]
Maybe losing $a000-$bfff to ROM can simply be placed under "future improvements" section.

**Comment by jkotlinski** [comment]
done
